### ISSUE TITLE
Warning message "File was not opened in write mode" when saving in S3 storage

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#392]
I've just seen the following warning message in the logs of the celeryworker:
```
celeryworker_1  | [2019-11-29 13:00:30,793: INFO/ForkPoolWorker-2] Task topobank.taskapp.tasks.perform_analysis[918c8d47-ae6a-42fc-a17b-c3e8b03144ed] succeeded in 3.797067907988094s: None
celeryworker_1  | [2019-11-29 13:00:31,488: WARNING/ForkPoolWorker-2] Traceback (most recent call last):
celeryworker_1  | [2019-11-29 13:00:31,488: WARNING/ForkPoolWorker-2] File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] File "h5py/defs.pyx", line 1187, in h5py.defs.H5Idec_ref
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] File "h5py/h5fd.pyx", line 171, in h5py.h5fd.H5FD_fileobj_write
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] File "/opt/conda/lib/python3.7/site-packages/storages/backends/s3boto3.py", line 115, in write
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] raise AttributeError("File was not opened in write mode.")
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] AttributeError
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] :
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] File was not opened in write mode.
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] Exception ignored in:
celeryworker_1  | [2019-11-29 13:00:31,489: WARNING/ForkPoolWorker-2] 'h5py._objects.ObjectID.__dealloc__'
celeryworker_1  | [2019-11-29 13:00:31,490: WARNING/ForkPoolWorker-2] Traceback (most recent call last):
celeryworker_1  | [2019-11-29 13:00:31,490: WARNING/ForkPoolWorker-2] File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
celeryworker_1  | [2019-11-29 13:00:31,490: WARNING/ForkPoolWorker-2] File "h5py/defs.pyx", line 1187, in h5py.defs.H5Idec_ref
celeryworker_1  | [2019-11-29 13:00:31,490: WARNING/ForkPoolWorker-2] File "h5py/h5fd.pyx", line 171, in h5py.h5fd.H5FD_fileobj_write
celeryworker_1  | [2019-11-29 13:00:31,491: WARNING/ForkPoolWorker-2] File "/opt/conda/lib/python3.7/site-packages/storages/backends/s3boto3.py", line 115, in write
celeryworker_1  | [2019-11-29 13:00:31,491: WARNING/ForkPoolWorker-2] raise AttributeError("File was not opened in write mode.")
celeryworker_1  | [2019-11-29 13:00:31,491: WARNING/ForkPoolWorker-2] AttributeError
celeryworker_1  | [2019-11-29 13:00:31,491: WARNING/ForkPoolWorker-2] :
celeryworker_1  | [2019-11-29 13:00:31,491: WARNING/ForkPoolWorker-2] File was not opened in write mode.
celeryworker_1  | [2019-11-29 13:00:44,098: INFO/ForkPoolWorker-2] Task topobank.taskapp.tasks.perform_analysis[88277d1a-d876-46f6-9942-26ec380504f0] succeeded in 13.30223007593304s: None
```
Not sure if this important.

**Comment by pastewka** [comment]
Does this issue still exist @mcrot ?

**Comment by mcrot** [comment]
No, closing.
