### ISSUE TITLE
Mail link for broken topographies does not work as expected on Chrome

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#429]
When a topography cannot be loaded any more, you see an error message similar to this:
![grafik](https://user-images.githubusercontent.com/9113541/72900540-5c046700-3d28-11ea-8ccf-7b0a43fd30a1.png)
When clicking the "mailto" link, your mail client opens up and you have a body message like
```
Hey there,

I've problems with 'contact.engineering'.

Here are some details:

Context: Bandwidth data calculation
Error message: Topography '10x10.ibw' (id: 157) cannot be loaded unexpectedly.
Traceback:
------------------------------------------------------------------------

Traceback (most recent call last):
  File "/app/topobank/manager/utils.py", line 303, in _bandwidths_data_entry
    pyco_topo = topo.topography()
  File "/app/topobank/manager/models.py", line 205, in topography
    toporeader = get_topography_reader(self.datafile, format=self.datafile_format)
  File "/app/topobank/manager/utils.py", line 70, in get_topography_reader
    return open_topography(filefield, format=format)
  File "/opt/conda/lib/python3.7/site-packages/PyCo/Topography/IO/__init__.py", line 170, in open_topography
    raise CannotDetectFileFormat(msg)
PyCo.Topography.IO.Reader.CannotDetectFileFormat: tried AscReader:  'utf-8' codec can't decode byte 0xec in position 2: invalid continuation byte

tried DIReader:  Header line '�ì�������d�������������g4346���������������������������' does not start with a slash.

tried MatReader:  Mat 4 mopt wrong format, byteswapping problem?

tried OPDReader:  Error reading directory block. Header is 'ì', expected 'Directory'

tried OPDxReader:  Invalid file format for Dektak OPDx.

tried X3PReader:  File is not a zip file

tried XYZReader:  'utf-8' codec can't decode byte 0xec in position 2: invalid continuation byte

tried IBWReader:  Invalid file format.

tried MIReader:  expected str, bytes or os.PathLike object, not FieldFile

tried NCReader:  [Errno 2] No such file or directory: b'topographies/user_2/10x10.ibw'

tried H5Reader:  Unable to create file (file signature not found)

tried NPYReader:  stat: path should be string, bytes, os.PathLike or integer, not FieldFile



------------------------------------------------------------------------


Best, <your name>
```

This works with firefox, but with Chrome the body is not accepted:
```
Hey there
```

It seems like Chrome stops using the body text, when a comma appears or sth. similar.

**Comment by pastewka** [comment]
This part of the user interface no longer exists.
