### ISSUE TITLE
Production: Database error because of too many clients

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#436]
Yesterday, the website showed an internal error. Probably related are many many messages
in the PostGreSQL logs:
```
[...]
postgres_1      | 2020-02-11T16:36:29.045202882Z 2020-02-11 16:36:29.045 UTC [28082] FATAL:  sorry, too many clients already
postgres_1      | 2020-02-11T16:43:55.384648517Z 2020-02-11 16:43:55.384 UTC [28098] FATAL:  sorry, too many clients already
postgres_1      | 2020-02-11T16:50:51.442620437Z 2020-02-11 16:50:51.442 UTC [28113] FATAL:  sorry, too many clients already
postgres_1      | 2020-02-11T16:56:47.498261314Z 2020-02-11 16:56:47.498 UTC [28126] FATAL:  sorry, too many clients already
```

I don't know what has caused this - I think these messages are related to the internal error, since a restart only of the database fixed it.

**Comment by mcrot** [comment]
Unfortunately this happens again:

```
django_1        | 2020-06-11T22:19:02.883567546Z Traceback (most recent call last):
django_1        | 2020-06-11T22:19:02.883572223Z   File "/opt/conda/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
django_1        | 2020-06-11T22:19:02.883577138Z     self.connect()
django_1        | 2020-06-11T22:19:02.883581745Z   File "/opt/conda/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
django_1        | 2020-06-11T22:19:02.883586592Z     self.connection = self.get_new_connection(conn_params)
django_1        | 2020-06-11T22:19:02.883591239Z   File "/opt/conda/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
django_1        | 2020-06-11T22:19:02.883596163Z     connection = Database.connect(**conn_params)
django_1        | 2020-06-11T22:19:02.883600788Z   File "/opt/conda/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
django_1        | 2020-06-11T22:19:02.883605663Z     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django_1        | 2020-06-11T22:19:02.883617442Z psycopg2.OperationalError: FATAL:  sorry, too many clients already
```

The fix from last time seems to be in place. Maybe the number of connections have to be increased?

**Comment by mcrot** [comment]
The application did not stop, but this error could accumulate somehow as in the past.

**Comment by mcrot** [comment]
Happened again when starting release v0.10.1 the first time. As workaround I've increased the
number of connections and the shared buffer:
```
    entrypoint: /docker-entrypoint.sh -c "shared_buffers=2GB" -c "max_connections=2000"
``` 
I don't know yet what caused the problem.

**Comment by mcrot** [comment]
Didn't happen since December 9th last year, when we started out new setup. Closing.
