### ISSUE TITLE
Power spectrum issue: Index out of bounds

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#496]
We got an bug report via mail:
```
> Analysis ID: 29884
> 
> Analysis Function: 'Power Spectrum'
> 
> Topography ID: 1702
> 
> Analysis State: failure
> 
> Error message: index -1 is out of bounds for axis 0 with size 0
> 
> ------------------------------------------------------------------------
> 
> Traceback (most recent call last):
> 
>    File "/app/topobank/taskapp/tasks.py", line 105, in perform_analysis
> 
>      result = analysis.function.eval(topography, **kwargs)
> 
>    File "/app/topobank/analysis/models.py", line 158, in eval
> 
>      return self.python_function(*args, **kwargs)
> 
>    File "/app/topobank/analysis/functions.py", line 503, in power_spectrum
> 
>      nbins=len(q_1D) - 1)
> 
>   File 
> "/opt/conda/lib/python3.7/site-packages/PyCo/Topography/HeightContainer.py", 
> line 75, in func
> 
>      return self._functions[name](self, *args, **kwargs)
> 
>    File 
> "/opt/conda/lib/python3.7/site-packages/PyCo/Topography/Uniform/PowerSpectrum.py", 
> line 182, in power_spectrum_2D
> 
>      C_qk, 2*np.pi*nx/(2*sx), nbins, physical_sizes=(2*np.pi*nx/sx, 
> 2*np.pi*ny/sy))
> 
>    File 
> "/opt/conda/lib/python3.7/site-packages/PyCo/Topography/common.py", line 
> 93, in radial_average
> 
>      if dr_max > dr_r[-1]:
> 
> IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by pastewka** [comment]
I've never seen this and think it is difficult to reproduce. Closing the issue.
