### ISSUE TITLE
Cannot detect File format for .npy file

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/TopoBank#503]
"Cannot determine file format of file 'test.npy'.Please try another file or contact us."

The numpy file was generated using 
```python
np.save("test.npy", np.array([0.1,1.,4,7.]))
```

Same issue with 2D data 

```python
np.save("test.npy", np.array([[0.1,1.],[4,7.]]))
```

Can be opend in PyCo 0.54
```
open_topography("test.npy").topography(physical_sizes=(1.,1.))
```

**Comment by mcrot** [comment]
Thanks. It can also be opened with PyCo 0.56.0 and SurfaceTopography 0.91.0. I'll have a look at this.

**Comment by mcrot** [comment]
I've had a closer look - it can be opened by SurfaceTopography 0.91.0, but not from an already opened binary stream:
```
In [25]: r = open_topography(open('example-2d.npy', mode='rb'))
---------------------------------------------------------------------------
CannotDetectFileFormat                    Traceback (most recent call last)
<ipython-input-25-d7acf498d764> in <module>
----> 1 r = open_topography(open('example-2d.npy', mode='rb'))

~/miniconda3/envs/topobank/lib/python3.7/site-packages/SurfaceTopography/IO/__init__.py in open_topography(fobj, format, communicator)
    185                     # has to be set back to the top of the file
    186                     fobj.seek(0)
--> 187         raise CannotDetectFileFormat(msg)
    188     else:
    189         if format not in lookup_reader_by_format.keys():

CannotDetectFileFormat: tried AscReader: 
 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

tried DIReader: 
 Header line 'NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (2, 2), }' does not start with a slash.

tried MatReader: 
 Unknown mat file type, version 32, 32

tried OPDReader: 
 Error reading directory block. Header is 'UMPY', expected 'Directory'

tried OPDxReader: 
 Invalid file format for Dektak OPDx.

tried X3PReader: 
 File is not a zip file

tried XYZReader: 
 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

tried IBWReader: 
 Invalid file format.

tried MIReader: 
 

tried NCReader: 
 [Errno 2] No such file or directory: b"<_io.BufferedReader name='example-2d.npy'>"

tried H5Reader: 
 Unable to open file (file signature not found)

tried NPYReader: 
 stat: path should be string, bytes, os.PathLike or integer, not _io.BufferedReader

```
TopoBank needs to read from an opened binary stream.

**Comment by mcrot** [comment]
Opened an issue here: https://github.com/ComputationalMechanics/SurfaceTopography/issues/39

**Comment by mcrot** [comment]
Although version 0.91.4 of `SurfaceTopography` is out now, I still have a problem loading these files in TopoBank:
``` 
[2020-10-19 11:22:16,867: ERROR/ForkPoolWorker-5] Task topobank.taskapp.tasks.perform_analysis[5c05cb11-c2ee-4017-9f26-474836e12144] raised unexpected: TypeError('stat: path should be string, bytes, os.PathLike or integer, not FieldFile')
Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/michael/prj/imtek/topobank/topobank/taskapp/tasks.py", line 101, in perform_analysis
    topography = Topography.objects.get(id=analysis.topography_id).topography()
  File "/home/michael/prj/imtek/topobank/topobank/manager/models.py", line 371, in topography
    toporeader = get_topography_reader(self.datafile, format=self.datafile_format)
  File "/home/michael/prj/imtek/topobank/topobank/manager/utils.py", line 92, in get_topography_reader
    return open_topography(filefield, format=format)
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/site-packages/SurfaceTopography/IO/__init__.py", line 193, in open_topography
    return lookup_reader_by_format[format](fobj, **kwargs)
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/site-packages/SurfaceTopography/IO/NPY.py", line 82, in __init__
    format="npy")
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/site-packages/NuMPI/IO/MPIFileIO.py", line 172, in make_mpi_file_view
    if not os.path.isfile(fn):
  File "/home/michael/miniconda3/envs/topobank/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not FieldFile
```
I'm going to investigate .. if you have any idea, @AntoineSIMTEK , let me know. Passing a `FieldFile` instance is not a problem for the other formats. I wonder whether we can replace `https://docs.python.org/3/library/os.path.html#os.path.isfile`.

**Comment by AntoineSIMTEK** [comment]
if not os.path.isfile(fn):

Is exactly the line I removed to fix the big

**Comment by mcrot** [comment]
Ah yes, sorry - I have to change setup.py such that the new `NumPI` version is installed. Forgot this, we've chatted about this on Friday.

**Comment by mcrot** [comment]
Created a PR on that: https://github.com/ComputationalMechanics/SurfaceTopography/pull/42

**Comment by mcrot** [comment]
With SurfaceTopography version 0.91.5, the 2D data can be loaded from an npy file.
I still face problems when loading a 1D file. Probably [this issue](https://github.com/ComputationalMechanics/SurfaceTopography/issues/43) in SurfaceTopography has to be solved first.

**Comment by mcrot** [comment]
I'm shifting this to the next release.

**Comment by pastewka** [comment]
This is not crucial, I am removing this from the v1.0.0 milestone
