### ISSUE TITLE
Only run average analyses for surfaces if at least 2 measurements

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#616]
So far analyses for surfaces are only shown if there are more than one topography.
The system still attempts to run them which can lead to unexpected error messages like
```
Traceback (most recent call last):
  File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 278, in eval
    return self._implementation(subject_type).eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 330, in eval
    return pyfunc(subject, **kwargs)
  File "/app/topobank/analysis/functions.py", line 750, in variable_bandwidth_for_surface
    result = average_results_for_surface(surface, topo_analysis_func=variable_bandwidth,
  File "/app/topobank/analysis/functions.py", line 580, in average_results_for_surface
    result_series.append(average_series_list(series_list, num_points=num_points, xscale='log'))
  File "/app/topobank/analysis/functions.py", line 489, in average_series_list
    interpol = interp1d(s['x'], s['y'], bounds_error=False)  # inserts NaN outside of boundaries
  File "/opt/conda/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 536, in __init__
    raise ValueError("x and y arrays must have at "
ValueError: x and y arrays must have at least 2 entries
```
Solution: Only trigger the average analyses if there is more than one measurement.

**Comment by mcrot** [comment]
This is not needed for v0.10.0, because in general this is visible to the user, since only surface analyses
are shown if there is more than one topography.
