### ISSUE TITLE
Curvature Distribution analysis fails for uniform line scans

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#663]
In version 0.11.1, the curvature distribution fails for uniform line scans:
```
Traceback (most recent call last):File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis\n    result = analysis.function.eval(subject, **kwargs)\n  File "/app/topobank/analysis/models.py", line 288, in eval\n    return self.get_implementation(subject_type).eval(subject, **kwargs)\n  File "/app/topobank/analysis/models.py", line 340, in eval\n    return pyfunc(subject, **kwargs)\n  File "/app/topobank/analysis/functions.py", line 308, in curvature_distribution\n    rms_curv = topography.rms_curvature_from_area() if topography.dim == 2 else topography.rms_curvature_from_profile()\n  File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/HeightContainer.py", line 85, in __getattr__\n    \', \'.join(self._functions.keys())))\nAttributeError: Unkown attribute \'rms_curvature_from_profile\' and no analysis or pipeline function of this name registered (class DetrendedUniformTopography). Available functions: mean, min, max, scale, detrend, transpose, translate, to_matrix, to_netcdf, to_nonuniform, make_fft, bandwidth, derivative, fourier_derivative, domain_decompose, plot, fill_undefined_data, mirror_stitch, interpolate_bicubic, interpolate_fourier, window, filter, shortcut, longcut, autocorrelation_from_profile, autocorrelation_from_area, power_spectrum_from_profile, power_spectrum_from_area, rms_height_from_profile, rms_height_from_area, rms_gradient, rms_slope_from_profile, rms_laplacian, rms_curvature_from_area, checkerboard_detrend, variable_bandwidth, scale_dependent_curvature_1D, scale_dependent_curvature_2D, scale_dependent_slope_1D, scale_dependent_slope_2D\n
```
It seems that the cause is https://github.com/ContactEngineering/SurfaceTopography/issues/95 .. see discussion there.
Upgrade `SurfaceTopography` if needed.

**Comment by mcrot** [comment]
Will be fixed in version 0.13.0.
