### ISSUE TITLE
Problems when calculation curvature distribution: supplied range of [nan, nan] is not finite

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#680]
After installation of version 0.13.0 and recalculating all curvature distribution analyses, I see several messages
like
```python
celeryworker_1  | 2021-06-16T13:26:00.162998082Z [2021-06-16 15:26:00,162: ERROR/ForkPoolWorker-3] Task topobank.taskapp.tasks.perform_analysis[2364aa7d-a5ff-4a2b-9921-e60ca296f3e8] raised unexpected: ValueError('supplied range of [nan, nan] is not finite')
celeryworker_1  | 2021-06-16T13:26:00.163021434Z Traceback (most recent call last):
celeryworker_1  | 2021-06-16T13:26:00.163025501Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  | 2021-06-16T13:26:00.163028864Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2021-06-16T13:26:00.163032895Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  | 2021-06-16T13:26:00.163036763Z     return self.run(*args, **kwargs)
celeryworker_1  | 2021-06-16T13:26:00.163039747Z   File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis
celeryworker_1  | 2021-06-16T13:26:00.163042729Z     result = analysis.function.eval(subject, **kwargs)
celeryworker_1  | 2021-06-16T13:26:00.163045406Z   File "/app/topobank/analysis/models.py", line 288, in eval
celeryworker_1  | 2021-06-16T13:26:00.163048281Z     return self.get_implementation(subject_type).eval(subject, **kwargs)
celeryworker_1  | 2021-06-16T13:26:00.163051166Z   File "/app/topobank/analysis/models.py", line 340, in eval
celeryworker_1  | 2021-06-16T13:26:00.163054009Z     return pyfunc(subject, **kwargs)
celeryworker_1  | 2021-06-16T13:26:00.163056660Z   File "/app/topobank/analysis/functions.py", line 315, in curvature_distribution
celeryworker_1  | 2021-06-16T13:26:00.163070037Z     density=True)
celeryworker_1  | 2021-06-16T13:26:00.163073123Z   File "<__array_function__ internals>", line 6, in histogram
celeryworker_1  | 2021-06-16T13:26:00.163077083Z   File "/opt/conda/lib/python3.7/site-packages/numpy/lib/histograms.py", line 792, in histogram
celeryworker_1  | 2021-06-16T13:26:00.163080020Z     bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
celeryworker_1  | 2021-06-16T13:26:00.163082876Z   File "/opt/conda/lib/python3.7/site-packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
celeryworker_1  | 2021-06-16T13:26:00.163085715Z     first_edge, last_edge = _get_outer_edges(a, range)
celeryworker_1  | 2021-06-16T13:26:00.163088470Z   File "/opt/conda/lib/python3.7/site-packages/numpy/lib/histograms.py", line 316, in _get_outer_edges
celeryworker_1  | 2021-06-16T13:26:00.163091523Z     "supplied range of [{}, {}] is not finite".format(first_edge, last_edge))
celeryworker_1  | 2021-06-16T13:26:00.163094435Z ValueError: supplied range of [nan, nan] is not finite
```

**Comment by mcrot** [comment]
Not sure whether these errors have been already there before the update, it happens roughly 60 times.
I've extracted the data from one case and loaded it separately:
```python
In [1]: from SurfaceTopography.IO import open_topography

In [2]: r=open_topography("../data/issues/680/issue_680.OPDx")

In [3]: r.default_channel.physical_sizes
Out[3]: (471.5613017402419, 353.5788024776325)

In [4]: r.default_channel.height_scale_factor
Out[4]: 1

In [5]: t=r.topography()

In [6]: t.rms_curvature_from_area()
Out[6]: nan
```
So during the calculation `nan` is returned.

**Comment by pastewka** [comment]
This topography has missing data points, related to #321
