### ISSUE TITLE
Error message in logs: Average for variable bandwidth fails

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#681]
```python
celeryworker_1  | 2021-06-16T13:42:47.605417146Z [2021-06-16 15:42:47,605: WARNING/ForkPoolWorker-5] /app/topobank/analysis/functions.py:493: RuntimeWarning: Mean of empty slice
celeryworker_1  | 2021-06-16T13:42:47.605437008Z   av_y = np.nanmean(interpol_y_list, axis=0)  # ignores NaNs generated by interpolation
celeryworker_1  | 2021-06-16T13:42:47.620368366Z [2021-06-16 15:42:47,620: ERROR/ForkPoolWorker-6] Task topobank.taskapp.tasks.perform_analysis[b33d759a-a303-44a9-b1b8-6d73f1719a7a] raised unexpected: ValueError('x and y arrays must have at least 2 entries')
celeryworker_1  | 2021-06-16T13:42:47.620398692Z Traceback (most recent call last):
celeryworker_1  | 2021-06-16T13:42:47.620402125Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  | 2021-06-16T13:42:47.620405326Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2021-06-16T13:42:47.620407977Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  | 2021-06-16T13:42:47.620410795Z     return self.run(*args, **kwargs)
celeryworker_1  | 2021-06-16T13:42:47.620421863Z   File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis
celeryworker_1  | 2021-06-16T13:42:47.620424708Z     result = analysis.function.eval(subject, **kwargs)
celeryworker_1  | 2021-06-16T13:42:47.620427326Z   File "/app/topobank/analysis/models.py", line 288, in eval
celeryworker_1  | 2021-06-16T13:42:47.620430026Z     return self.get_implementation(subject_type).eval(subject, **kwargs)
celeryworker_1  | 2021-06-16T13:42:47.620432732Z   File "/app/topobank/analysis/models.py", line 340, in eval
celeryworker_1  | 2021-06-16T13:42:47.620435369Z     return pyfunc(subject, **kwargs)
celeryworker_1  | 2021-06-16T13:42:47.620437950Z   File "/app/topobank/analysis/functions.py", line 786, in variable_bandwidth_for_surface
celeryworker_1  | 2021-06-16T13:42:47.620440721Z     storage_prefix=storage_prefix)
celeryworker_1  | 2021-06-16T13:42:47.620443344Z   File "/app/topobank/analysis/functions.py", line 580, in average_results_for_surface
celeryworker_1  | 2021-06-16T13:42:47.620445996Z     result_series.append(average_series_list(series_list, num_points=num_points, xscale='log'))
celeryworker_1  | 2021-06-16T13:42:47.620448727Z   File "/app/topobank/analysis/functions.py", line 489, in average_series_list
celeryworker_1  | 2021-06-16T13:42:47.620451487Z     interpol = interp1d(s['x'], s['y'], bounds_error=False)  # inserts NaN outside of boundaries
celeryworker_1  | 2021-06-16T13:42:47.620454559Z   File "/opt/conda/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 537, in __init__
celeryworker_1  | 2021-06-16T13:42:47.620457315Z     "least %d entries" % minval)
celeryworker_1  | 2021-06-16T13:42:47.620459969Z ValueError: x and y arrays must have at least 2 entries
```

When did this happen and why?

**Comment by mcrot** [comment]
This happened for the average with 2/3/4 measurements. The analyses for the single measurements worked.

**Comment by mcrot** [comment]
This can be reproduced by having this simple topography in a surface:
```
0 1
1 1
2 2
3 1
4 1
5 1
```

The variable bandwidth has only one point as result:
```
{'name': 'Variable-bandwidth analysis',
 'xlabel': 'Bandwidth',
 'ylabel': 'RMS Height',
 'xunit': 'nm',
 'yunit': 'nm',
 'xscale': 'log',
 'yscale': 'log',
 'series': [{'name': 'Variable-bandwidth analysis',
   'x': array([7.]),
   'y': array([0.34992711])}]}
```
This cannot be used for interpolation.

**Comment by mcrot** [comment]
I've improved the exception, but did not take efforts to generalize the average results, since
this event should be quite unusual. Additionally, this is now output as an expected situation,
a warning than an exception.
