### ISSUE TITLE
Failure during Power Spectrum analysis: Positions not sorted

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#683]
In production there is a non-uniform line scan with two values given for the same position.
The power spectrum analysis fails:
```
eleryworker_1  | 2021-06-16T15:02:26.476419644Z [2021-06-16 17:02:26,476: ERROR/ForkPoolWorker-7] Task topobank.taskapp.tasks.perform_analysis[29cb960c-eb1a-45ac-8448-3bd49bfd8e6a] raised unexpected: RuntimeError('Positions not sorted.')
celeryworker_1  | 2021-06-16T15:02:26.476441972Z Traceback (most recent call last):
celeryworker_1  | 2021-06-16T15:02:26.476445934Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  | 2021-06-16T15:02:26.476449559Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2021-06-16T15:02:26.476453439Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  | 2021-06-16T15:02:26.476456887Z     return self.run(*args, **kwargs)
celeryworker_1  | 2021-06-16T15:02:26.476460080Z   File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis
celeryworker_1  | 2021-06-16T15:02:26.476463491Z     result = analysis.function.eval(subject, **kwargs)
celeryworker_1  | 2021-06-16T15:02:26.476466614Z   File "/app/topobank/analysis/models.py", line 288, in eval
celeryworker_1  | 2021-06-16T15:02:26.476470154Z     return self.get_implementation(subject_type).eval(subject, **kwargs)
celeryworker_1  | 2021-06-16T15:02:26.476473355Z   File "/app/topobank/analysis/models.py", line 340, in eval
celeryworker_1  | 2021-06-16T15:02:26.476476591Z     return pyfunc(subject, **kwargs)
celeryworker_1  | 2021-06-16T15:02:26.476479743Z   File "/app/topobank/analysis/functions.py", line 356, in power_spectrum
celeryworker_1  | 2021-06-16T15:02:26.476483356Z     q_1D, C_1D = topography.power_spectrum_from_profile(window=window)
celeryworker_1  | 2021-06-16T15:02:26.476486901Z   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/HeightContainer.py", line 76, in func
celeryworker_1  | 2021-06-16T15:02:26.476490284Z     return self._functions[name](self, *args, **kwargs)
celeryworker_1  | 2021-06-16T15:02:26.476493404Z   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/Nonuniform/PowerSpectrum.py", line 156, in power_spectrum
celeryworker_1  | 2021-06-16T15:02:26.476496712Z     raise RuntimeError('Positions not sorted.')
celeryworker_1  | 2021-06-16T15:02:26.476499854Z RuntimeError: Positions not sorted.
```

This can be reproduced by this simple data:
```python
In [20]: cat testdata.asc
0 1
1 1
2 1
2 2
3 2
4 2


In [21]: r=open_topography("testdata.asc")

In [22]: t=r.topography()

In [23]: t.power_spectrum_from_profile()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-c4cdb9b170cd> in <module>
----> 1 t.power_spectrum_from_profile()

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/HeightContainer.py in func(*args, **kwargs)
     74         if name in self._functions:
     75             def func(*args, **kwargs):
---> 76                 return self._functions[name](self, *args, **kwargs)
     77 
     78             func.__doc__ = self._functions[name].__doc__

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/Nonuniform/PowerSpectrum.py in power_spectrum(line_scan, algorithm, wavevectors, ninterpolate, short_cutoff, window)
    154         min_dist = np.min(np.diff(x))
    155         if min_dist <= 0:
--> 156             raise RuntimeError('Positions not sorted.')
    157         wavevectors, psd = line_scan.to_uniform(
    158             ninterpolate * int(s / min_dist), 0).power_spectrum_from_profile(window=window)

RuntimeError: Positions not sorted.
```

Should I catch this error on TopoBank side? Or should this be handled differently by `SurfaceTopography`, @AntoineSIMTEK and @pastewka ?

**Comment by pastewka** [comment]
This is a reentrant surface for which a PSD cannot be calculated. You should catch this on the TopoBank side, but we should probably change the error message (mentioning that PSD cannot be computed for reentrant surfaces).

**Comment by mcrot** [comment]
This surface also causes problems with other analyses:

## Slope Distribution
```python
Traceback (most recent call last):
  File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject,
**kwargs)
  File "/app/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
  File "/app/topobank/analysis/functions.py", line 277, in
slope_distribution
    scalars_slope_x, series_slope_x =
_moments_histogram_gaussian(dh_dx, bins=bins,
  File "/app/topobank/analysis/functions.py", line 190, in
_moments_histogram_gaussian
    hist, bin_edges = np.histogram(arr, bins=bins, density=True,
  File "<__array_function__ internals>", line 5, in histogram
  File "/opt/conda/lib/python3.8/site-
packages/numpy/lib/histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/opt/conda/lib/python3.8/site-
packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/opt/conda/lib/python3.8/site-
packages/numpy/lib/histograms.py", line 315, in _get_outer_edges
    raise ValueError(
ValueError: supplied range of [0.0, inf] is not finite
```

## Curvature Distribution
```python
Traceback (most recent call last):
  File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject,
**kwargs)
  File "/app/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
  File "/app/topobank/analysis/functions.py", line 313, in
curvature_distribution
    hist, bin_edges = np.histogram(hist_arr, bins=bins,
  File "<__array_function__ internals>", line 5, in histogram
  File "/opt/conda/lib/python3.8/site-
packages/numpy/lib/histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/opt/conda/lib/python3.8/site-
packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/opt/conda/lib/python3.8/site-
packages/numpy/lib/histograms.py", line 315, in _get_outer_edges
    raise ValueError(
ValueError: supplied range of [-inf, inf] is not finite
```
## Power Spectrum (as this issue, for completeness)
```python
Traceback (most recent call last):
  File "/app/topobank/taskapp/tasks.py", line 127, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject,
**kwargs)
  File "/app/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
  File "/app/topobank/analysis/functions.py", line 356, in
power_spectrum
    q_1D, C_1D = topography.power_spectrum_from_profile(window=window)
  File "/opt/conda/lib/python3.8/site-
packages/SurfaceTopography/HeightContainer.py", line 76, in func
    return self._functions[name](self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-
packages/SurfaceTopography/Nonuniform/PowerSpectrum.py", line 156, in
power_spectrum
    raise RuntimeError('Positions not sorted.')
RuntimeError: Positions not sorted.
```

Similar for **AutoCorrelation** and **ScaleDependentSlope**!

## Roughness Parameters

Not in the analysis, but in the UI!

![grafik](https://user-images.githubusercontent.com/9113541/123075796-d4d58a00-d418-11eb-82c1-bad3a2724ffe.png)
