### ISSUE TITLE
Analyses stopped working

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#709]
In #707 and #708, analyses were not completed. I've created this issues here for root analysis.

One thing I notice that it starts with a missing heartbeat of the message broker:
```
celeryworker_1  | 2021-08-16T07:52:55.715024824Z [2021-08-16 09:52:10,748: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
celeryworker_1  | 2021-08-16T07:52:57.082885828Z Traceback (most recent call last):
celeryworker_1  | 2021-08-16T07:52:57.540637091Z   File "/opt/conda/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
celeryworker_1  | 2021-08-16T07:52:58.107901949Z     blueprint.start(self)
celeryworker_1  | 2021-08-16T07:52:58.117149680Z   File "/opt/conda/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celeryworker_1  | 2021-08-16T07:52:58.117166818Z     step.start(parent)
celeryworker_1  | 2021-08-16T07:52:58.117170363Z   File "/opt/conda/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
celeryworker_1  | 2021-08-16T07:52:58.117173616Z     c.loop(*c.loop_args())
celeryworker_1  | 2021-08-16T07:52:58.117176683Z   File "/opt/conda/lib/python3.7/site-packages/celery/worker/loops.py", line 81, in asynloop
celeryworker_1  | 2021-08-16T07:52:58.117180040Z     next(loop)
celeryworker_1  | 2021-08-16T07:52:58.117183080Z   File "/opt/conda/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 300, in create_loop
celeryworker_1  | 2021-08-16T07:52:58.117186300Z     poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
celeryworker_1  | 2021-08-16T07:52:58.117189613Z   File "/opt/conda/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 142, in fire_timers
celeryworker_1  | 2021-08-16T07:52:58.117192703Z     entry()
celeryworker_1  | 2021-08-16T07:52:58.117195713Z   File "/opt/conda/lib/python3.7/site-packages/kombu/asynchronous/timer.py", line 65, in __call__
celeryworker_1  | 2021-08-16T07:52:58.117200083Z     return self.fun(*self.args, **self.kwargs)
celeryworker_1  | 2021-08-16T07:52:58.117203144Z   File "/opt/conda/lib/python3.7/site-packages/kombu/asynchronous/timer.py", line 127, in _reschedules
celeryworker_1  | 2021-08-16T07:52:58.117206233Z     return fun(*args, **kwargs)
celeryworker_1  | 2021-08-16T07:52:58.117209185Z   File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 307, in heartbeat_check
celeryworker_1  | 2021-08-16T07:52:58.117212231Z     return self.transport.heartbeat_check(self.connection, rate=rate)
celeryworker_1  | 2021-08-16T07:52:58.117215188Z   File "/opt/conda/lib/python3.7/site-packages/kombu/transport/pyamqp.py", line 181, in heartbeat_check
celeryworker_1  | 2021-08-16T07:52:58.117218844Z     return connection.heartbeat_tick(rate=rate)
celeryworker_1  | 2021-08-16T07:52:58.117223462Z   File "/opt/conda/lib/python3.7/site-packages/amqp/connection.py", line 768, in heartbeat_tick
celeryworker_1  | 2021-08-16T07:52:58.117227810Z     raise ConnectionForced('Too many heartbeats missed')
celeryworker_1  | 2021-08-16T07:52:58.117232524Z amqp.exceptions.ConnectionForced: Too many heartbeats missed
celeryworker_1  | 2021-08-16T07:53:18.356098984Z [2021-08-16 09:52:58,466: WARNING/MainProcess] /opt/conda/lib/python3.7/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
celeryworker_1  | 2021-08-16T07:53:18.419467447Z In Celery 5.1 we introduced an optional breaking change which
celeryworker_1  | 2021-08-16T07:53:18.469549623Z on connection loss cancels all currently executed tasks with late acknowledgement enabled.
celeryworker_1  | 2021-08-16T07:53:18.469569335Z These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
celeryworker_1  | 2021-08-16T07:53:18.469572538Z You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
celeryworker_1  | 2021-08-16T07:53:18.469575300Z In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.
celeryworker_1  | 2021-08-16T07:53:18.469578185Z 
celeryworker_1  | 2021-08-16T07:53:18.469580839Z   warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)
celeryworker_1  | 2021-08-16T07:53:18.469583505Z 
celeryworker_1  | 2021-08-16T07:54:28.793402693Z [2021-08-16 09:54:28,792: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: timed out.
celeryworker_1  | 2021-08-16T07:54:28.805168465Z Trying again in 2.00 seconds... (1/100)
```
A fraction of a second later, the connection was back, but a worker was killed:
```
celeryworker_1  | 2021-08-16T07:54:28.805188091Z 
celeryworker_1  | 2021-08-16T07:54:31.809687753Z [2021-08-16 09:54:31,808: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
celeryworker_1  | 2021-08-16T07:54:31.997934741Z [2021-08-16 09:54:31,996: INFO/MainProcess] mingle: searching for neighbors
celeryworker_1  | 2021-08-16T07:54:36.777132185Z [2021-08-16 09:54:36,776: INFO/MainProcess] mingle: all alone
celeryworker_1  | 2021-08-16T12:31:44.804651873Z [2021-08-16 14:31:44,803: INFO/MainProcess] Task topobank.taskapp.tasks.renew_topography_thumbnail[e737685e-1179-43af-83ed-28cf875953e7] received
celeryworker_1  | 2021-08-16T12:31:44.883748077Z [2021-08-16 14:31:44,817: INFO/MainProcess] Task topobank.taskapp.tasks.renew_analyses_related_to_topography[c1d69967-7e5e-4d09-b282-df77ec039e5d] received
celeryworker_1  | 2021-08-16T12:31:45.508037648Z INFO 2021-08-16 14:31:45,492 utils 38 140608654615936 Deleting all analyses for topography 5572..
celeryworker_1  | 2021-08-16T12:31:45.513514082Z [2021-08-16 14:31:45,492: INFO/ForkPoolWorker-8] Deleting all analyses for topography 5572..
celeryworker_1  | 2021-08-16T12:31:45.694978715Z INFO 2021-08-16 14:31:45,694 utils 38 140608654615936 Triggering analyses for topography 5572 and all analysis functions..
celeryworker_1  | 2021-08-16T12:31:45.695001610Z [2021-08-16 14:31:45,694: INFO/ForkPoolWorker-8] Triggering analyses for topography 5572 and all analysis functions..
celeryworker_1  | 2021-08-16T12:31:46.570528266Z [2021-08-16 14:31:46,570: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[22010e2e-7a2e-4913-ad60-5a30a93471c0] received
celeryworker_1  | 2021-08-16T12:31:46.720915520Z [2021-08-16 14:31:46,720: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[0d13476c-42ad-4e63-9aaf-0f6159fda80a] received
celeryworker_1  | 2021-08-16T12:31:46.788174906Z [2021-08-16 14:31:46,787: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[33bef961-f94a-4118-8590-59e5c33d09c5] received
celeryworker_1  | 2021-08-16T12:31:46.872631832Z [2021-08-16 14:31:46,872: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[101e1026-b56f-4e2e-9275-52fe5f76b923] received
celeryworker_1  | 2021-08-16T12:31:46.955753443Z [2021-08-16 14:31:46,955: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[45fb779a-0236-4204-a6fa-3c4e3acbcfeb] received
celeryworker_1  | 2021-08-16T12:31:47.027701426Z [2021-08-16 14:31:47,027: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[5151e572-f78d-4256-b005-d87193007af0] received
celeryworker_1  | 2021-08-16T12:31:47.096937731Z [2021-08-16 14:31:47,096: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[b8b70e0f-a29e-48fe-b192-26959cfda6bc] received
celeryworker_1  | 2021-08-16T12:31:47.207013813Z [2021-08-16 14:31:47,206: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[ed4ec806-ec77-4759-8507-fe395efbdfce] received
celeryworker_1  | 2021-08-16T12:31:47.277496772Z [2021-08-16 14:31:47,277: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[3b105fb3-12a4-4166-b80b-d02c55a3ce9f] received
celeryworker_1  | 2021-08-16T12:31:47.289448881Z INFO 2021-08-16 14:31:47,289 models 38 140608654615936 Regenerating analyses directly related to surface 1104..
celeryworker_1  | 2021-08-16T12:31:47.289471227Z [2021-08-16 14:31:47,289: INFO/ForkPoolWorker-8] Regenerating analyses directly related to surface 1104..
celeryworker_1  | 2021-08-16T12:31:47.291990428Z INFO 2021-08-16 14:31:47,291 utils 38 140608654615936 Deleting all analyses for surface 1104..
celeryworker_1  | 2021-08-16T12:31:47.292012782Z [2021-08-16 14:31:47,291: INFO/ForkPoolWorker-8] Deleting all analyses for surface 1104..
celeryworker_1  | 2021-08-16T12:31:47.312185248Z INFO 2021-08-16 14:31:47,311 utils 38 140608654615936 Triggering analyses for surface 1104 and all analysis functions..
celeryworker_1  | 2021-08-16T12:31:47.312214331Z [2021-08-16 14:31:47,311: INFO/ForkPoolWorker-8] Triggering analyses for surface 1104 and all analysis functions..
celeryworker_1  | 2021-08-16T12:31:47.336969460Z [2021-08-16 14:31:47,336: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[4fbbd56c-7926-42d4-9fa6-f01ce5355de0] received
celeryworker_1  | 2021-08-16T12:31:47.397805305Z [2021-08-16 14:31:47,397: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[3dcd6e30-968a-4080-9652-14543bc9516e] received
celeryworker_1  | 2021-08-16T12:31:47.411974468Z [2021-08-16 14:31:47,411: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[8fac1055-fd4e-4a64-a97d-1e6ea2cce0dd] received
celeryworker_1  | 2021-08-16T12:31:47.423184729Z [2021-08-16 14:31:47,422: INFO/MainProcess] Task topobank.taskapp.tasks.perform_analysis[5b6e62d1-a48d-45ac-b80c-1005052892ea] received
celeryworker_1  | 2021-08-16T12:31:47.506445858Z [2021-08-16 14:31:47,506: INFO/ForkPoolWorker-8] Task topobank.taskapp.tasks.renew_analyses_related_to_topography[c1d69967-7e5e-4d09-b282-df77ec039e5d] succeeded in 2.3598727779462934s: None
celeryworker_1  | 2021-08-16T12:32:14.137623969Z [2021-08-16 14:32:14,031: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:32 exited with 'signal 9 (SIGKILL)'
celeryworker_1  | 2021-08-16T12:32:15.442845271Z [2021-08-16 14:32:14,959: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 2913.')
celeryworker_1  | 2021-08-16T12:32:15.442878624Z Traceback (most recent call last):
celeryworker_1  | 2021-08-16T12:32:15.442882535Z   File "/opt/conda/lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
celeryworker_1  | 2021-08-16T12:32:15.442886319Z     human_status(exitcode), job._job),
celeryworker_1  | 2021-08-16T12:32:15.442889323Z billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 2913.
```
This continued with `MemoryError` while loading a Matlab data file:
```
celeryworker_1  | 2021-08-16T12:32:15.442878624Z Traceback (most recent call last):
celeryworker_1  | 2021-08-16T12:32:15.442882535Z   File "/opt/conda/lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
celeryworker_1  | 2021-08-16T12:32:15.442886319Z     human_status(exitcode), job._job),
celeryworker_1  | 2021-08-16T12:32:15.442889323Z billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 2913.
celeryworker_1  | 2021-08-16T12:32:17.359635934Z ERROR 2021-08-16 14:32:17,359 models 38 140608654615936 Could not create squeezed datafile for topography with id 5572. Using original 
file instead.
celeryworker_1  | 2021-08-16T12:32:17.403412365Z [2021-08-16 14:32:17,359: ERROR/ForkPoolWorker-8] Could not create squeezed datafile for topography with id 5572. Using original file i
nstead.
celeryworker_1  | 2021-08-16T12:32:17.781453720Z ERROR 2021-08-16 14:32:17,090 models 37 140608654615936 Could not create squeezed datafile for topography with id 5572. Using original 
file instead.
celeryworker_1  | 2021-08-16T12:32:17.786920478Z [2021-08-16 14:32:17,090: ERROR/ForkPoolWorker-7] Could not create squeezed datafile for topography with id 5572. Using original file i
nstead.
celeryworker_1  | 2021-08-16T12:32:19.424625890Z ERROR 2021-08-16 14:32:17,548 models 36 140608654615936 Could not create squeezed datafile for topography with id 5572. Using original 
file instead.
celeryworker_1  | 2021-08-16T12:32:19.425289952Z [2021-08-16 14:32:17,548: ERROR/ForkPoolWorker-6] Could not create squeezed datafile for topography with id 5572. Using original file i
nstead.
celeryworker_1  | 2021-08-16T12:32:25.650593081Z ERROR 2021-08-16 14:32:25,600 models 35 140608654615936 Could not create squeezed datafile for topography with id 5572. Using original 
file instead.
celeryworker_1  | 2021-08-16T12:32:25.651271428Z [2021-08-16 14:32:25,600: ERROR/ForkPoolWorker-5] Could not create squeezed datafile for topography with id 5572. Using original file i
nstead.
celeryworker_1  | 2021-08-16T12:33:08.595510205Z ERROR 2021-08-16 14:33:08,561 models 33 140608654615936 Could not create squeezed datafile for topography with id 5572. Using original 
file instead.
celeryworker_1  | 2021-08-16T12:33:08.615853349Z [2021-08-16 14:33:08,561: ERROR/ForkPoolWorker-3] Could not create squeezed datafile for topography with id 5572. Using original file i
nstead.
celeryworker_1  | 2021-08-16T12:33:09.158541881Z ERROR 2021-08-16 14:33:08,823 models 31 140608654615936 Could not create squeezed datafile for topography with id 5572. Using original 
file instead.
celeryworker_1  | 2021-08-16T12:33:09.301829197Z [2021-08-16 14:33:08,823: ERROR/ForkPoolWorker-1] Could not create squeezed datafile for topography with id 5572. Using original file i
nstead.
celeryworker_1  | 2021-08-16T12:33:16.088611787Z [2021-08-16 14:33:16,087: ERROR/ForkPoolWorker-5] Task topobank.taskapp.tasks.perform_analysis[45fb779a-0236-4204-a6fa-3c4e3acbcfeb] ra
ised unexpected: MemoryError()
celeryworker_1  | 2021-08-16T12:33:16.088639798Z Traceback (most recent call last):
celeryworker_1  | 2021-08-16T12:33:16.088643798Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
celeryworker_1  | 2021-08-16T12:33:16.088647150Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2021-08-16T12:33:16.088650381Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
celeryworker_1  | 2021-08-16T12:33:16.088653557Z     return self.run(*args, **kwargs)
celeryworker_1  | 2021-08-16T12:33:16.088656568Z   File "/app/topobank/taskapp/tasks.py", line 129, in perform_analysis
celeryworker_1  | 2021-08-16T12:33:16.088659738Z     result = analysis.function.eval(subject, **kwargs)
celeryworker_1  | 2021-08-16T12:33:16.088662743Z   File "/app/topobank/analysis/models.py", line 288, in eval
celeryworker_1  | 2021-08-16T12:33:16.088665844Z     return self.get_implementation(subject_type).eval(subject, **kwargs)
celeryworker_1  | 2021-08-16T12:33:16.088670612Z   File "/app/topobank/analysis/models.py", line 340, in eval
celeryworker_1  | 2021-08-16T12:33:16.088673677Z     return pyfunc(subject, **kwargs)
celeryworker_1  | 2021-08-16T12:33:16.088676578Z   File "/app/topobank/analysis/functions.py", line 664, in autocorrelation
celeryworker_1  | 2021-08-16T12:33:16.088679629Z     topography = topography.topography()
celeryworker_1  | 2021-08-16T12:33:16.088693184Z   File "/app/topobank/manager/models.py", line 600, in topography
celeryworker_1  | 2021-08-16T12:33:16.088696095Z     toporeader = get_topography_reader(self.datafile, format=self.datafile_format)
celeryworker_1  | 2021-08-16T12:33:16.088698738Z   File "/app/topobank/manager/utils.py", line 97, in get_topography_reader
celeryworker_1  | 2021-08-16T12:33:16.088701369Z     reader = open_topography(filefield, format=format)
celeryworker_1  | 2021-08-16T12:33:16.088704040Z   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/__init__.py", line 200, in open_topography
celeryworker_1  | 2021-08-16T12:33:16.088706843Z     return lookup_reader_by_format[format](fobj, **kwargs)
celeryworker_1  | 2021-08-16T12:33:16.088709411Z   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/Matlab.py", line 61, in __init__
celeryworker_1  | 2021-08-16T12:33:16.088712104Z     data = loadmat(fobj)
celeryworker_1  | 2021-08-16T12:33:16.088714701Z   File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 226, in loadmat
celeryworker_1  | 2021-08-16T12:33:16.088717353Z     matfile_dict = MR.get_variables(variable_names)
celeryworker_1  | 2021-08-16T12:33:16.088720211Z   File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio5.py", line 332, in get_variables
celeryworker_1  | 2021-08-16T12:33:16.088722901Z     res = self.read_var_array(hdr, process)
celeryworker_1  | 2021-08-16T12:33:16.088725827Z   File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio5.py", line 292, in read_var_array
celeryworker_1  | 2021-08-16T12:33:16.088728498Z     return self._matrix_reader.array_from_header(header, process)
celeryworker_1  | 2021-08-16T12:33:16.088731630Z   File "mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
celeryworker_1  | 2021-08-16T12:33:16.088734435Z   File "mio5_utils.pyx", line 701, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
celeryworker_1  | 2021-08-16T12:33:16.088737199Z   File "mio5_utils.pyx", line 775, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
celeryworker_1  | 2021-08-16T12:33:16.088739828Z   File "mio5_utils.pyx", line 448, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
celeryworker_1  | 2021-08-16T12:33:16.088743212Z   File "mio5_utils.pyx", line 353, in scipy.io.matlab.mio5_utils.VarReader5.read_element
celeryworker_1  | 2021-08-16T12:33:16.088747143Z   File "streams.pyx", line 173, in scipy.io.matlab.streams.ZlibInputStream.read_string
celeryworker_1  | 2021-08-16T12:33:16.088750844Z   File "pyalloc.pxd", line 9, in scipy.io.matlab.pyalloc.pyalloc_v
celeryworker_1  | 2021-08-16T12:33:16.088754479Z MemoryError
celeryworker_1  | 2021-08-16T12:33:19.626083926Z [2021-08-16 14:33:19,623: ERROR/ForkPoolWorker-3] Task topobank.taskapp.tasks.perform_analysis[33bef961-f94a-4118-8590-59e5c33d09c5] raised unexpected: MemoryError()
```
Here more worker processes are killed:
```
celeryworker_1  | 2021-08-16T12:33:19.626111517Z Traceback (most recent call last):
celeryworker_1  | 2021-08-16T12:33:19.626115846Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
celeryworker_1  | 2021-08-16T12:33:19.626119196Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2021-08-16T12:33:19.626122232Z   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
celeryworker_1  | 2021-08-16T12:33:19.626125355Z     return self.run(*args, **kwargs)
celeryworker_1  | 2021-08-16T12:33:19.626135742Z   File "/app/topobank/taskapp/tasks.py", line 129, in perform_analysis
celeryworker_1  | 2021-08-16T12:33:19.626138592Z     result = analysis.function.eval(subject, **kwargs)
celeryworker_1  | 2021-08-16T12:33:19.626141205Z   File "/app/topobank/analysis/models.py", line 288, in eval
celeryworker_1  | 2021-08-16T12:33:19.626143850Z     return self.get_implementation(subject_type).eval(subject, **kwargs)
celeryworker_1  | 2021-08-16T12:33:19.626146667Z   File "/app/topobank/analysis/models.py", line 340, in eval
celeryworker_1  | 2021-08-16T12:33:19.626149300Z     return pyfunc(subject, **kwargs)
celeryworker_1  | 2021-08-16T12:33:19.626151872Z   File "/app/topobank/analysis/functions.py", line 310, in curvature_distribution
celeryworker_1  | 2021-08-16T12:33:19.626154527Z     topography = topography.topography()
celeryworker_1  | 2021-08-16T12:33:19.626157134Z   File "/app/topobank/manager/models.py", line 600, in topography
celeryworker_1  | 2021-08-16T12:33:19.626159753Z     toporeader = get_topography_reader(self.datafile, format=self.datafile_format)
celeryworker_1  | 2021-08-16T12:33:19.626162358Z   File "/app/topobank/manager/utils.py", line 97, in get_topography_reader
celeryworker_1  | 2021-08-16T12:33:19.626165097Z     reader = open_topography(filefield, format=format)
celeryworker_1  | 2021-08-16T12:33:19.626167717Z   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/__init__.py", line 200, in open_topography
celeryworker_1  | 2021-08-16T12:33:19.626170436Z     return lookup_reader_by_format[format](fobj, **kwargs)
celeryworker_1  | 2021-08-16T12:33:19.626172951Z   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/Matlab.py", line 61, in __init__
celeryworker_1  | 2021-08-16T12:33:19.626175660Z     data = loadmat(fobj)
celeryworker_1  | 2021-08-16T12:33:19.626178264Z   File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 226, in loadmat
celeryworker_1  | 2021-08-16T12:33:19.626180935Z     matfile_dict = MR.get_variables(variable_names)
celeryworker_1  | 2021-08-16T12:33:19.626183490Z   File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio5.py", line 332, in get_variables
celeryworker_1  | 2021-08-16T12:33:19.626186172Z     res = self.read_var_array(hdr, process)
celeryworker_1  | 2021-08-16T12:33:19.626188732Z   File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio5.py", line 292, in read_var_array
celeryworker_1  | 2021-08-16T12:33:19.626191379Z     return self._matrix_reader.array_from_header(header, process)
celeryworker_1  | 2021-08-16T12:33:19.626194564Z   File "mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
celeryworker_1  | 2021-08-16T12:33:19.626197274Z   File "mio5_utils.pyx", line 701, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
celeryworker_1  | 2021-08-16T12:33:19.626199944Z   File "mio5_utils.pyx", line 775, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
celeryworker_1  | 2021-08-16T12:33:19.626202558Z   File "mio5_utils.pyx", line 448, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
celeryworker_1  | 2021-08-16T12:33:19.626205151Z   File "mio5_utils.pyx", line 353, in scipy.io.matlab.mio5_utils.VarReader5.read_element
celeryworker_1  | 2021-08-16T12:33:19.626207751Z   File "streams.pyx", line 173, in scipy.io.matlab.streams.ZlibInputStream.read_string
celeryworker_1  | 2021-08-16T12:33:19.626213201Z   File "pyalloc.pxd", line 9, in scipy.io.matlab.pyalloc.pyalloc_v
celeryworker_1  | 2021-08-16T12:33:19.626215934Z MemoryError
celeryworker_1  | 2021-08-16T12:33:20.579214661Z [2021-08-16 14:33:20,578: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:37 exited with 'signal 9 (SIGKILL)'
celeryworker_1  | 2021-08-16T12:33:20.589616033Z [2021-08-16 14:33:20,589: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:34 exited with 'signal 9 (SIGKILL)'
celeryworker_1  | 2021-08-16T12:33:20.621290790Z [2021-08-16 14:33:20,620: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 2910.')
celeryworker_1  | 2021-08-16T12:33:20.621313536Z Traceback (most recent call last):
celeryworker_1  | 2021-08-16T12:33:20.621316747Z   File "/opt/conda/lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
celeryworker_1  | 2021-08-16T12:33:20.621319740Z     human_status(exitcode), job._job),
celeryworker_1  | 2021-08-16T12:33:20.621322501Z billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 2910.
```
This continued until now more workers were left and a manual restart of the `celeryworker` container was needed.

**Comment by mcrot** [comment]
Should be checked again when running on a larger machine.

**Comment by mcrot** [comment]
I've restarted the analyses for surface 1104 on the larger machine. Unfortunately, the error still happens:
```python3
021-12-06T09:37:18.535773928Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | INFO 2021-12-06 10:37:18,535 models 218 139626414911744 Using squeezed datafile instead of original d
atafile for topography id 5572.
2021-12-06T09:37:18.535833454Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | [2021-12-06 10:37:18,535: INFO/ForkPoolWorker-2] Using squeezed datafile instead of original datafile
 for topography id 5572.
2021-12-06T09:37:18.756737101Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | INFO 2021-12-06 10:37:18,756 models 249 139626414911744 Using squeezed datafile instead of original datafile for topography id 5572.
2021-12-06T09:37:18.756869519Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | [2021-12-06 10:37:18,756: INFO/ForkPoolWorker-33] Using squeezed datafile instead of original datafile for topography id 5572.
2021-12-06T09:37:47.588016172Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | [2021-12-06 10:37:47,535: ERROR/MainProcess] Process 'ForkPoolWorker-49' pid:83866 exited with 'signal 9 (SIGKILL)'
2021-12-06T09:37:47.715687525Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | [2021-12-06 10:37:47,676: ERROR/MainProcess] Pool callback raised exception: Error('error 26 from memcached_get(celery-task-meta-c38ff86e-bbc9-4): Transport endpoint is not connected')
2021-12-06T09:37:47.715749271Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | Traceback (most recent call last):
2021-12-06T09:37:47.715776773Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
2021-12-06T09:37:47.715784601Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     raise WorkerLostError(
2021-12-06T09:37:47.715792096Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 12185.
2021-12-06T09:37:47.715798726Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | 
2021-12-06T09:37:47.715804192Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | During handling of the above exception, another exception occurred:
2021-12-06T09:37:47.715811833Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | 
2021-12-06T09:37:47.715818033Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | Traceback (most recent call last):
2021-12-06T09:37:47.715825746Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
2021-12-06T09:37:47.715832248Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     fun(*args, **kwargs)
2021-12-06T09:37:47.715838945Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/celery/worker/request.py", line 571, in on_failure
2021-12-06T09:37:47.715846483Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     self.task.backend.mark_as_failure(
2021-12-06T09:37:47.715853379Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/celery/backends/base.py", line 171, in mark_as_failure
2021-12-06T09:37:47.715860647Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     self.store_result(task_id, exc, state,
2021-12-06T09:37:47.715866504Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/celery/backends/base.py", line 482, in store_result
2021-12-06T09:37:47.715873784Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     self._store_result(task_id, result, state, traceback,
2021-12-06T09:37:47.715879439Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/celery/backends/base.py", line 903, in _store_result
2021-12-06T09:37:47.715896842Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     current_meta = self._get_task_meta_for(task_id)
2021-12-06T09:37:47.715902788Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/celery/backends/base.py", line 925, in _get_task_meta_for
2021-12-06T09:37:47.715920401Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     meta = self.get(self.get_key_for_task(task_id))
2021-12-06T09:37:47.715927464Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |   File "/opt/conda/lib/python3.9/site-packages/celery/backends/cache.py", line 120, in get
2021-12-06T09:37:47.715934627Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    |     return self.client.get(key)
2021-12-06T09:37:47.715943336Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | pylibmc.Error: error 26 from memcached_get(celery-task-meta-c38ff86e-bbc9-4): Transport endpoint is not connected
2021-12-06T09:38:09.727419210Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | [2021-12-06 10:38:09,697: ERROR/MainProcess] Process 'ForkPoolWorker-33' pid:249 exited with 'signal 9 (SIGKILL)'
2021-12-06T09:38:09.749465529Z prodstack_celeryworker.1.uwb9apj9r13f@analyses    | [2021-12-06 10:38:09,748: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 12187.')
```
(excerpt)

The related measurement is really large:
```python3
In [1]: from topobank.manager.models import Topography

In [2]: t=Topography.objects.get(id=5572)

In [3]: t.size_x
Out[3]: 16524.0

In [4]: t.size_y
Out[4]: 3398.0
```
The calculation of height distribution worked, for all other there seem to be difficulties (not fully sure).

@pastewka , @AntoineSIMTEK should such a big measurement work in general with 100GB RAM?

Maybe the processes competed for memory and there was not enough available at the same time.
Maybe we need to shuffle the analyses in a more intelligent way, e.g. using queues for big jobs so they are
processed one by one in order to make use of the large RAM.

**Comment by AntoineSIMTEK** [comment]
One single analysis should definitely fit into the 100Gb. But you will run into problems if many of them run in parallel.

**Comment by pastewka** [comment]
Not sure if this is still an issue. Closing it.
