### ISSUE TITLE
Failure during PSD for line scans

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#734]
I've just tried the current setup in Docker and recalculated some analysis.
PSD for line scan failed for uniform and non-uniform line scans like follows:

```python3
Traceback (most recent call last):
  File "/app/topobank/taskapp/tasks.py", line 129, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
  File "/app/topobank/analysis/functions.py", line 559, in power_spectrum
    return analysis_function(topography,
  File "/app/topobank/analysis/functions.py", line 426, in analysis_function
    r, A = func(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/SurfaceTopography/HeightContainer.py", line 89, in func
    return self._functions[name](self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Nonuniform/PowerSpectrum.py", line 177, in power_spectrum
    wavevectors, psd = self.to_uniform(nb_interpolate=nb_interpolate) \
  File "/opt/conda/lib/python3.8/site-packages/SurfaceTopography/HeightContainer.py", line 89, in func
    return self._functions[name](self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Uniform/PowerSpectrum.py", line 122, in power_spectrum_from_profile
    q, _, C, _ = resample(q, C_all, min_value=q[1], max_value=short_cutoff, collocation=collocation,
  File "/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Support/Regression.py", line 301, in resample
    collocation_points, bin_edges = make_grid(collocation, min_value, max_value, nb_points=nb_points,
  File "/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Support/Regression.py", line 81, in make_grid
    bin_edges = np.linspace(np.log10(min_value), np.log10(max_value), nb_points)
  File "<__array_function__ internals>", line 5, in linspace
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/function_base.py", line 122, in linspace
    raise ValueError("Number of samples, %s, must be non-negative." % num)
ValueError: Number of samples, -25, must be non-negative.
```

**Comment by mcrot** [comment]
This happens because of the instrument setting, which was maybe not appropriate for the topography.
First the topography with instrument settings, `t` and `t2` are `SurfaceTopography.NonlinearLineScan` containers :

```python3
In [29]: t.positions()     
Out[29]: array([0. , 1. , 2. , 3.5, 4. , 5. , 6. ]) 
                                                                                                                                                                                                                   
In [30]: t.heights()                 
Out[30]: 
array([-0.16666667, -0.16666667, -0.16666667,  0.83333333, -0.16666667,                                                                                                                                            
       -0.16666667, -0.16666667])                                                                        
                                                    
In [31]: t.info                                     
Out[31]:                                                                                                                                                                                                           
{'instrument': {'name': 'Bla',         
  'type': 'microscope-based',                                                                                                                                                                                      
  'parameters': {'resolution': {'unit': 'µm', 'value': 10.0}}},                             
 'unit': 'nm'}                                                                                           
                                                    
In [32]: t.power_spectrum_from_profile()            
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)                              
<ipython-input-32-c4cdb9b170cd> in <module>                                                                                                                                                                        
----> 1 t.power_spectrum_from_profile()
                                                    
/opt/conda/lib/python3.8/site-packages/SurfaceTopography/HeightContainer.py in func(*args, **kwargs)
     87         if name in self._functions:     
     88             def func(*args, **kwargs):
---> 89                 return self._functions[name](self, *args, **kwargs)                              
     90                                                                                                  
     91             func.__doc__ = self._functions[name].__doc__                                         
                                                                                                         
/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Nonuniform/PowerSpectrum.py in power_spectrum(self, reliable, algorithm, wavevectors, nb_interpolate, short_cutoff, window, resampling_method, collocation
, nb_points, nb_points_per_decade)       
    175             raise RuntimeError('This topography is reentrant (i.e. it contains overhangs). The power-spectral '                                                                                            
    176                                'density cannot be computed for reentrant topographies.')
--> 177         wavevectors, psd = self.to_uniform(nb_interpolate=nb_interpolate) \                      
    178             .power_spectrum_from_profile(window=window, reliable=reliable, resampling_method=resampling_method,                                                                                            
    179                                          collocation=collocation, nb_points=nb_points, 


/opt/conda/lib/python3.8/site-packages/SurfaceTopography/HeightContainer.py in func(*args, **kwargs)
     87         if name in self._functions:
     88             def func(*args, **kwargs):
---> 89                 return self._functions[name](self, *args, **kwargs)
     90 
     91             func.__doc__ = self._functions[name].__doc__

/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Uniform/PowerSpectrum.py in power_spectrum_from_profile(self, window, reliable, resampling_method, collocation, nb_points, nb_points_per_decade)
    120             q = np.resize(q, (C_all.shape[1], q.shape[0])).T.ravel()
    121             C_all = np.ravel(C_all)
--> 122         q, _, C, _ = resample(q, C_all, min_value=q[1], max_value=short_cutoff, collocation=collocation,
    123                               nb_points=nb_points, nb_points_per_decade=nb_points_per_decade, method=resampling_method)
    124         return q, C

/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Support/Regression.py in resample(x, values, collocation, nb_points, min_value, max_value, nb_points_per_decade, method)
    299         min_value = np.min(x)
    300 
--> 301     collocation_points, bin_edges = make_grid(collocation, min_value, max_value, nb_points=nb_points,
    302                                               nb_points_per_decade=nb_points_per_decade)
    303 

/opt/conda/lib/python3.8/site-packages/SurfaceTopography/Support/Regression.py in make_grid(collocation, min_value, max_value, nb_points, nb_points_per_decade)
     79             # => dl = np.log(2)
     80             nb_points = int(np.ceil((np.log10(max_value) - np.log10(min_value) + 1) * nb_points_per_decade))
---> 81         bin_edges = np.linspace(np.log10(min_value), np.log10(max_value), nb_points)
     82         collocation_points = 10 ** ((bin_edges[1:] + bin_edges[:-1]) / 2)
     83         bin_edges = 10 ** bin_edges

<__array_function__ internals> in linspace(*args, **kwargs)

/opt/conda/lib/python3.8/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    120     num = operator.index(num)
    121     if num < 0:
--> 122         raise ValueError("Number of samples, %s, must be non-negative." % num)
    123     div = (num - 1) if endpoint else num
    124 

ValueError: Number of samples, -25, must be non-negative.
```

Without the instrument setting, there is no exception:

```python 3
In [33]: t2=NonuniformLineScan(t.positions(), t.heights())  #  without info

In [34]: t2.power_spectrum_from_profile()
Out[34]: 
(array([2.23388487, 2.54135381, 2.89114237, 3.14159265, 3.74177931,
        4.1887902 , 4.84269214, 5.23598776]),
 array([       nan,        nan,        nan, 0.06749945,        nan,
        0.01788558,        nan, 0.00861214]))
```

@pastewka do you have an idea, how we should handle this when calling the analysis function in the web app?

Or should we catch this in SurfaceTopography?

**Comment by pastewka** [comment]
This looks like there is not data that is reliable. In this case, the analysis function should probably return empty lists or raise an exception (a la no data available).

@mcrot - what do you think is more reasonable?

**Comment by mcrot** [comment]
I think it's more reasonable to raise an exception here. 
If there was simply no data point visible, the user would search for points and think it's broken.

Instead an exception becomes visible at a prominent place. Maybe we can reraise an `IncompatibleTopographyException`
which appears more like a warning or notice. This is then like "Contact Mechanics is not implemented for line scans":
![grafik](https://user-images.githubusercontent.com/9113541/135849018-fd0ccce2-696f-4992-aa69-39176c62d460.png)
It could say instead **Analysis is nowhere reliable for this kind of analysis.**

One open question for me is, how to detect this case.
It seems too general for me to interpret all `ValueError` like this if they come out of power spectrum calculation.

Is there a way to use `t.short_reliability_cutoff()` beforehand in order to find which analyses will have no result?
Or should `SurfaceTopography` always return an empty result of no data is reliable?

**Comment by pastewka** [comment]
We don't have dedicated error classes in SurfaceTopography, but I think we should add them. We could make an explicity error `NoReliableDataError` or something like this. Similarly, we should probably add a `DataIsReentrantError` (you have something like this in TopoBank).

This would be an API change and I would make a new release for this (which is of course fine). What do you think?

**Comment by mcrot** [comment]
Sounds good and makes it super simple for me to detect such cases!

**Comment by pastewka** [comment]
See here: https://github.com/ContactEngineering/SurfaceTopography/pull/150 - discussion welcome

**Comment by mcrot** [comment]
Should we include this extension of `SurfaceTopography` in the new version of the web app? 

In the web app, I have a list of exceptions, which are regarded as meaning "analysis incompatible with measurement".
I think I can just add the exception base class `SurfaceTopography.Exceptions.CannotPerformAnalysisError` to that list.

So far as I know, the analysis function in TopoBank do not depend on specific exceptions from SurfaceTopography so far,
so this should work smoothly.

**Comment by pastewka** [comment]
Sounds good, I've justed release 0.98.0, may take a couple of minutes until it's on PyPI

**Comment by mcrot** [comment]
Thank you!

**Comment by pastewka** [comment]
Slope and curvature and VBM should also raise the "NoReliableData" condition.

Also, if there is no reliable data, we should still show the unreliable portion of the PSD, ACF, etc.

**Comment by pastewka** [comment]
(PS: I will fix this on the `SurfaceTopography` side.)

**Comment by mcrot** [comment]
> (PS: I will fix this on the `SurfaceTopography` side.)

Thanks. I also had this Traceback when the workers tried to update the Surface analysis:
```python3
[2021-10-06 09:59:44,183: ERROR/ForkPoolWorker-2] Task topobank.taskapp.tasks.perform_analysis[98231c99-53f2-44cc-ac25-3b7080f2d972] raised unexpected: ValueError('Number of samples, -
29, must be non-negative.')
Traceback (most recent call last):
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/taskapp/tasks.py", line 131, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/functions.py", line 750, in scale_dependent_slope_for_surface
    return scale_dependent_roughness_parameter_for_surface(
  File "/home/michael/work/imtek/topobank/topobank/analysis/functions.py", line 713, in scale_dependent_roughness_parameter_for_surface
    distances, rms_values_sq = scale_dependent_statistical_property(
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/Container/ScaleDependentStatistics.py", line 134, in scale_dependent_statistical_property
    existing_distances = np.logspace(lower_decade, upper_decade,
  File "<__array_function__ internals>", line 5, in logspace
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/numpy/core/function_base.py", line 275, in logspace
    y = linspace(start, stop, num=num, endpoint=endpoint, axis=axis)
  File "<__array_function__ internals>", line 5, in linspace
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/numpy/core/function_base.py", line 122, in linspace
    raise ValueError("Number of samples, %s, must be non-negative." % num)
ValueError: Number of samples, -29, must be non-negative.
```
This is probably related .. maybe `scale_dependent_statistical_property` could also throw the `NoReliableData` exception.

**Comment by pastewka** [comment]
This is related to the above problem and should be fixed with the PR below.

See here for a fix: https://github.com/ContactEngineering/SurfaceTopography/pull/151

Can you test whether this works in TopoBank or do I need to release it first?

**Comment by mcrot** [comment]
Thank you. I can test it without releasing by installing from the branch via `pip install .`.

**Comment by pastewka** [comment]
Okay great, let me know if it works.
