### ISSUE TITLE
Autocorrelation analysis for surface failed because of unexpected keyword

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#765]
```
Analysis ID: 236070
Analysis Function: 'Autocorrelation'
Subject Type: surface
Subject ID: 969
Analysis State: failure
Error message: autocorrelation_for_surface() got an unexpected keyword
argument 'num_points'
---------------------------------------------------------------------
---

Traceback (most recent call last):
  File "/app/topobank/taskapp/tasks.py", line 131, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject,
**kwargs)
  File "/app/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
TypeError: autocorrelation_for_surface() got an unexpected keyword
argument 'num_points'
```

**Comment by mcrot** [comment]
Duplicate of #772, closing.
