### ISSUE TITLE
Not enough arguments for contact mechanics calculation

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#777]
Error in production:
```python3
Internal Server Error: /analysis/card/contact-mechanics-data

TypeError at /analysis/card/contact-mechanics-data
function takes at least 2 arguments (1 given)

Request Method: POST
Request URL: https://contact.engineering/analysis/card/contact-mechanics-data
Django Version: 3.2.7
Python Executable: /opt/conda/bin/python
Python Version: 3.7.1
Python Path: ['/app', '/app', '/opt/conda/bin', '/opt/conda/lib/python37.zip', '/opt/conda/lib/python3.7', '/opt/conda/lib/python3.7/lib-dynload', '/opt/conda/lib/python3.7/site-packages', '/app/topobank']
Server time: Thu, 16 Dec 2021 12:26:22 +0100
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'collectfast',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.postgres',
 'crispy_forms',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.orcid',
 'rest_framework',
 'fontawesomefree',
 'formtools',
 'bokeh',
 'termsandconditions',
 'storages',
 'guardian',
 'bootstrap_datepicker_plus',
 'django_select2',
 'django_tables2',
 'progressbarupload',
 'celery_progress',
 'notifications',
 'django_filters',
 'tagulous',
 'trackstats',
 'fullurl',
 'topobank.users.apps.UsersAppConfig',
 'topobank.manager.apps.ManagerAppConfig',
 'topobank.analysis.apps.AnalysisAppConfig',
 'topobank.usage_stats.apps.UsageStatsAppConfig',
 'topobank.tabnav.apps.TabNavAppConfig',
 'topobank.publication.apps.PublicationAppConfig',
 'topobank.taskapp.celery.CeleryAppConfig',
 'gunicorn']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'termsandconditions.middleware.TermsAndConditionsRedirectMiddleware',
 'topobank.middleware.anonymous_user_middleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'topobank.usage_stats.middleware.count_request_middleware']


Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/topobank/analysis/views.py", line 1393, in contact_mechanics_data
    patch_ids = assign_patch_numbers(contacting_points)[1]

Exception Type: TypeError at /analysis/card/contact-mechanics-data
Exception Value: function takes at least 2 arguments (1 given)
```

**Comment by mcrot** [comment]
Closed by #758.
