### ISSUE TITLE
Keyerror on loading text file

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#781]
I've just seem the following error in the logs when recalculating squeezed files:
```
2022-01-17T10:32:34.945661856Z prodstack_celeryworker.1.uboizvvuhokn@analyses    | [2022-01-17 11:32:34,944: ERROR/ForkPoolWorker-2] Task topobank.taskapp.tasks.renew_squeezed_datafile[14281c44-94b6-4f16-af23-0a6133842eb1] raised unexpected: KeyError('× 10<sup>-6</sup>')
2022-01-17T10:32:34.945704206Z prodstack_celeryworker.1.uboizvvuhokn@analyses    | Traceback (most recent call last):
2022-01-17T10:32:34.945710880Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
2022-01-17T10:32:34.945716190Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     R = retval = fun(*args, **kwargs)
2022-01-17T10:32:34.945720413Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
2022-01-17T10:32:34.945725096Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     return self.run(*args, **kwargs)
2022-01-17T10:32:34.945729277Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/app/topobank/taskapp/tasks.py", line 275, in renew_squeezed_datafile
2022-01-17T10:32:34.945733982Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     topography.renew_squeezed_datafile()
2022-01-17T10:32:34.945738033Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/app/topobank/manager/models.py", line 1029, in renew_squeezed_datafile
2022-01-17T10:32:34.945742276Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     st_topo = self.topography(allow_cache=False, allow_squeezed=False)
2022-01-17T10:32:34.945746287Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/app/topobank/manager/models.py", line 687, in topography
2022-01-17T10:32:34.945750550Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     topo = toporeader.topography(**topography_kwargs)
2022-01-17T10:32:34.945754551Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/FromFile.py", line 132, in topography
2022-01-17T10:32:34.945758956Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     return reader_func(self._fobj, **reader_kwargs)
2022-01-17T10:32:34.945762913Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/common.py", line 55, in func_wrapper
2022-01-17T10:32:34.945767286Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     retvals = func(fobj_text, *args, **kwargs)
2022-01-17T10:32:34.945771225Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/Text.py", line 238, in read_asc
2022-01-17T10:32:34.945797197Z prodstack_celeryworker.1.uboizvvuhokn@analyses    |     xsiz *= length_units[xunit] / length_units[unit]
2022-01-17T10:32:34.945803701Z prodstack_celeryworker.1.uboizvvuhokn@analyses    | KeyError: '× 10<sup>-6</sup>'
```
It seems like that the corresponding data files are text files with headers like:
```
# Width: 2.500 × 10<sup>-6</sup>
# Height: 2.500 × 10<sup>-6</sup>
```
So `xunit` e.g. is interpreted as `× 10<sup>-6</sup>`.

We should display some error message at some point that this file has not the correct format.

**Comment by pastewka** [comment]
The user will now see an error message for those cases, fixed with #1012
