### ISSUE TITLE
Problems while calculation contact mechanics

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#783]
In roughly 1/3 of the cases the contact mechanics calculation fails with version 0.18.1.
Many times the following error is present:
```python
2022-01-21T10:21:05.018755080Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    | [2022-01-21 11:21:05,016: ERROR/ForkPoolWorker-12] Task topobank.taskapp.tasks.perform_analysis[6199915d-02d2-43ce-a1f7-bc68a30233f5] raised unexpected: ValueError('cannot convert float NaN to integer')
2022-01-21T10:21:05.018843028Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    | Traceback (most recent call last):
2022-01-21T10:21:05.018858223Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
2022-01-21T10:21:05.018870319Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     R = retval = fun(*args, **kwargs)
2022-01-21T10:21:05.018880390Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
2022-01-21T10:21:05.018890088Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     return self.run(*args, **kwargs)
2022-01-21T10:21:05.018899730Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/app/topobank/taskapp/tasks.py", line 131, in perform_analysis
2022-01-21T10:21:05.018910585Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     result = analysis.function.eval(subject, **kwargs)
2022-01-21T10:21:05.018919384Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/app/topobank/analysis/models.py", line 288, in eval
2022-01-21T10:21:05.018929099Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     return self.get_implementation(subject_type).eval(subject, **kwargs)
2022-01-21T10:21:05.018939801Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/app/topobank/analysis/models.py", line 340, in eval
2022-01-21T10:21:05.018949416Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     return pyfunc(subject, **kwargs)
2022-01-21T10:21:05.018959844Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/app/topobank/analysis/functions.py", line 1177, in contact_mechanics
2022-01-21T10:21:05.018970750Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     unit = suggest_length_unit_for_data('linear', gap_xy.data, topography.unit)
2022-01-21T10:21:05.018980582Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/Support/UnitConversion.py", line 209, in suggest_length_unit_for_data
2022-01-21T10:21:05.018990265Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     return suggest_length_unit(scale, fac * mn, fac * mx)
2022-01-21T10:21:05.019000434Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/Support/UnitConversion.py", line 156, in suggest_length_unit
2022-01-21T10:21:05.019045107Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    |     m10 = 3 * int(np.floor(np.log10(v) / 3))
2022-01-21T10:21:05.019055468Z prodstack_celeryworker.1.0ms4qtvswwj0@analyses    | ValueError: cannot convert float NaN to integer
```
It seems like `SurfaceTopography.Support.UnitConversion.suggest_length_unit` cannot deal with NaN.
@pastewka , is this an issue for SurfaceTopography or should these NaNs be filtered in TopoBank?

**Comment by pastewka** [comment]
Where do these NaNs come from? `suggest_length_unit` cannot deal with NaNs but there shouldn't be NaNs as input.

**Comment by mcrot** [comment]
```python3
unit = suggest_length_unit_for_data('linear', gap_xy.data, topography.unit)
```
It seems like that `gap_xy.data` has NaNs, since this function call uses min+max.
This e.g. happens, if the topography as NaN values.

Maybe we should use `np.nanmin` and `np.nanmax` inside `suggest_length_unit_for_data` if it is guaranteed that `gap_xy` has some finite values..

**Comment by pastewka** [comment]
I see, this is for topographies with missing data. I'll update SurfaceTopography asap. Is there other things that need changing there?

**Comment by mcrot** [comment]
Not yet, except of #755. Maybe we could double check the progress meter stuff there, although I think that is more related to the infrastructure (not sure yet).

**Comment by mcrot** [comment]
Hm - please wait with the release, there is some more I think. Let me create some issues and we have a look.

**Comment by pastewka** [comment]
I've fixed the NaN issue - let me know what more there is.

**Comment by mcrot** [comment]
Thanks. The other errors where related to memcached or its reachability, not to SurfaceTopography.

**Comment by pastewka** [comment]
I'll send you a PR in a second
