### ISSUE TITLE
Error on renewal of squeezed datafile

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#789]
While generating images, this happened:
```
2022-01-28T09:23:43.559665091Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | INFO 2022-01-28 10:23:43,559 models 123 140441924822400 Renewing squeezed datafile for topography 879..
2022-01-28T09:23:43.559715745Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | [2022-01-28 10:23:43,559: INFO/ForkPoolWorker-32] Renewing squeezed datafile for topography 879..
2022-01-28T09:23:47.139433775Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | [2022-01-28 10:23:47,138: WARNING/ForkPoolWorker-32] /opt/conda/lib/python3.7/site-packages/SurfaceTopography/UniformLineScanAndTopography.py:356: RuntimeWarning: divide by zero encountered in true_divide
2022-01-28T09:23:47.139510916Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   return np.asarray(self.physical_sizes) / np.asarray(self.nb_grid_pts)
2022-01-28T09:23:47.139523886Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | 
2022-01-28T09:23:47.147686804Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | [2022-01-28 10:23:47,146: ERROR/ForkPoolWorker-32] Task topobank.taskapp.tasks.renew_squeezed_datafile[9d78c440-8cc0-46b6-ba4d-141130046884] raised unexpected: TypeError("unsupported operand type(s) for +: 'ellipsis' and 'int'")
2022-01-28T09:23:47.147750410Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | Traceback (most recent call last):
2022-01-28T09:23:47.147762072Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
2022-01-28T09:23:47.147824196Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     R = retval = fun(*args, **kwargs)
2022-01-28T09:23:47.147834299Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
2022-01-28T09:23:47.147843310Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     return self.run(*args, **kwargs)
2022-01-28T09:23:47.147850703Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/taskapp/tasks.py", line 275, in renew_squeezed_datafile
2022-01-28T09:23:47.147857892Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     topography.renew_squeezed_datafile()
2022-01-28T09:23:47.147864731Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 1054, in renew_squeezed_datafile
2022-01-28T09:23:47.147872726Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     st_topo.to_netcdf(tmp.name)
2022-01-28T09:23:47.147879550Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/HeightContainer.py", line 90, in func
2022-01-28T09:23:47.147889531Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     return self._functions[name](self, *args, **kwargs)
2022-01-28T09:23:47.147896456Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/Support/Bibliography.py", line 71, in func_with_doi
2022-01-28T09:23:47.147903531Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     retvals = func(*args, **kwargs)
2022-01-28T09:23:47.147911172Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/SurfaceTopography/IO/NC.py", line 433, in write_nc_uniform
2022-01-28T09:23:47.147918194Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     x_var[...] = np.arange(nx) / nx * sx
2022-01-28T09:23:47.147925053Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/scipy/io/netcdf.py", line 1004, in __setitem__
2022-01-28T09:23:47.147933079Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     recs = rec_index + 1
2022-01-28T09:23:47.147942027Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | TypeError: unsupported operand type(s) for +: 'ellipsis' and 'int'
```

**Comment by mcrot** [comment]
This error was preceded by this one:
```
2022-01-28T09:23:43.554263555Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | [2022-01-28 10:23:43,553: WARNING/ForkPoolWorker-32] Problems while generating thumbnail for topography 879: Error generating 2D plot for topography.. Saving <None> instead.
2022-01-28T09:23:43.554981366Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | WARNING 2022-01-28 10:23:43,554 models 123 140441924822400 Traceback: Traceback (most recent call last):
2022-01-28T09:23:43.555013415Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 785, in get_plot
2022-01-28T09:23:43.555022433Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     return self._get_2d_plot(st_topo, reduced=thumbnail)
2022-01-28T09:23:43.555028595Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 874, in _get_2d_plot
2022-01-28T09:23:43.555035217Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     color_mapper = LinearColorMapper(palette="Viridis256", low=heights.min(), high=heights.max())
2022-01-28T09:23:43.555041307Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/numpy/core/_methods.py", line 44, in _amin
2022-01-28T09:23:43.555047505Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     return umr_minimum(a, axis, None, out, keepdims, initial, where)
2022-01-28T09:23:43.555053033Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | ValueError: zero-size array to reduction operation minimum which has no identity
2022-01-28T09:23:43.555058693Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | 
2022-01-28T09:23:43.555064043Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | The above exception was the direct cause of the following exception:
2022-01-28T09:23:43.555069774Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | 
2022-01-28T09:23:43.555075174Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | Traceback (most recent call last):
2022-01-28T09:23:43.555080541Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 1012, in renew_images
2022-01-28T09:23:43.555086344Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     self._renew_images(driver=driver)
2022-01-28T09:23:43.555091682Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 947, in _renew_images
2022-01-28T09:23:43.555097335Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     plot = self.get_plot(thumbnail=True)
2022-01-28T09:23:43.555102973Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 787, in get_plot
2022-01-28T09:23:43.555108691Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     raise PlotTopographyException("Error generating 2D plot for topography.") from exc
2022-01-28T09:23:43.555114996Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | topobank.manager.models.PlotTopographyException: Error generating 2D plot for topography.
2022-01-28T09:23:43.555120902Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | 
2022-01-28T09:23:43.555126052Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | [2022-01-28 10:23:43,554: WARNING/ForkPoolWorker-32] Traceback: Traceback (most recent call last):
2022-01-28T09:23:43.555159927Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 785, in get_plot
2022-01-28T09:23:43.555167427Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     return self._get_2d_plot(st_topo, reduced=thumbnail)
2022-01-28T09:23:43.555172897Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 874, in _get_2d_plot
2022-01-28T09:23:43.555178507Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     color_mapper = LinearColorMapper(palette="Viridis256", low=heights.min(), high=heights.max())
2022-01-28T09:23:43.555184660Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/opt/conda/lib/python3.7/site-packages/numpy/core/_methods.py", line 44, in _amin
2022-01-28T09:23:43.555190914Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     return umr_minimum(a, axis, None, out, keepdims, initial, where)
2022-01-28T09:23:43.555196729Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | ValueError: zero-size array to reduction operation minimum which has no identity
2022-01-28T09:23:43.555202175Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | 
2022-01-28T09:23:43.555207470Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | The above exception was the direct cause of the following exception:
2022-01-28T09:23:43.555213075Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | 
2022-01-28T09:23:43.555218225Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | Traceback (most recent call last):
2022-01-28T09:23:43.555223720Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 1012, in renew_images
2022-01-28T09:23:43.555229310Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     self._renew_images(driver=driver)
2022-01-28T09:23:43.555238194Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 947, in _renew_images
2022-01-28T09:23:43.555244133Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     plot = self.get_plot(thumbnail=True)
2022-01-28T09:23:43.555249483Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |   File "/app/topobank/manager/models.py", line 787, in get_plot
2022-01-28T09:23:43.555255192Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    |     raise PlotTopographyException("Error generating 2D plot for topography.") from exc
2022-01-28T09:23:43.555261378Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | topobank.manager.models.PlotTopographyException: Error generating 2D plot for topography.
2022-01-28T09:23:43.555267475Z prodstack_celeryworker.1.s9mqw4xgrvtn@analyses    | 
```
Not sure whether both are related.

**Comment by mcrot** [comment]
This seems to be a problem with SurfaceTopography. Opened an issue there: https://github.com/ContactEngineering/SurfaceTopography/issues/207

**Comment by pastewka** [comment]
Closing this as the whole upload/cache renewal mechanism has been rewritten with #1012
