### ISSUE TITLE
Celery error: Precondition failed, timeout in rabbitmq/Celery

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#791]
It seems that for big analysis, we're running into a timeout in of rabbitmq/celery:
```
2022-02-03T10:15:36.046540169Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    | [2022-02-03 11:15:36,020: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more', (0, 0), '')
2022-02-03T10:15:36.046688473Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    | Traceback (most recent call last):
2022-02-03T10:15:36.046705570Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
2022-02-03T10:15:36.046713871Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     self.blueprint.start(self)
2022-02-03T10:15:36.046721339Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
2022-02-03T10:15:36.046728847Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     step.start(parent)
2022-02-03T10:15:36.046746755Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
2022-02-03T10:15:36.046771023Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     return self.obj.start()
2022-02-03T10:15:36.046778258Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
2022-02-03T10:15:36.046785928Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     blueprint.start(self)
2022-02-03T10:15:36.046792493Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
2022-02-03T10:15:36.046798971Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     step.start(parent)
2022-02-03T10:15:36.046812449Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
2022-02-03T10:15:36.046820291Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     c.loop(*c.loop_args())
2022-02-03T10:15:36.046826522Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/celery/worker/loops.py", line 97, in asynloop
2022-02-03T10:15:36.046832894Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     next(loop)
2022-02-03T10:15:36.046839242Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
2022-02-03T10:15:36.046846117Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     cb(*cbargs)
2022-02-03T10:15:36.046852609Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/kombu/transport/base.py", line 235, in on_readable
2022-02-03T10:15:36.046858905Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     reader(loop)
2022-02-03T10:15:36.046865013Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/kombu/transport/base.py", line 217, in _read
2022-02-03T10:15:36.046871368Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     drain_events(timeout=0)
2022-02-03T10:15:36.046877406Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/amqp/connection.py", line 522, in drain_events
2022-02-03T10:15:36.046890740Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     while not self.blocking_read(timeout):
2022-02-03T10:15:36.046897376Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/amqp/connection.py", line 528, in blocking_read
2022-02-03T10:15:36.046904033Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     return self.on_inbound_frame(frame)
2022-02-03T10:15:36.046910338Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/amqp/method_framing.py", line 53, in on_frame
2022-02-03T10:15:36.046916692Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     callback(channel, method_sig, buf, None)
2022-02-03T10:15:36.046923442Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/amqp/connection.py", line 535, in on_inbound_method
2022-02-03T10:15:36.046957822Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     method_sig, payload, content,
2022-02-03T10:15:36.046968957Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/amqp/abstract_channel.py", line 143, in dispatch_method
2022-02-03T10:15:36.046992302Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     listener(*args)
2022-02-03T10:15:36.047000717Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |   File "/opt/conda/lib/python3.7/site-packages/amqp/channel.py", line 282, in _on_close
2022-02-03T10:15:36.047007958Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    |     reply_code, reply_text, (class_id, method_id), ChannelError,
2022-02-03T10:15:36.047014375Z prodstack_celeryworker.1.ryylut4gg9xg@analyses    | amqp.exceptions.PreconditionFailed: (0, 0): (406) PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
```
This is half an hour, which is quite long.
Not sure yet which timeout this is (https://www.rabbitmq.com/configure.html  or in celery).

**Comment by mcrot** [comment]
This can be configured here:
https://www.rabbitmq.com/consumers.html#acknowledgement-timeout

I'll try to set that to one hour as maximum length of an analysis task.

**Comment by pastewka** [comment]
That is not reasonable. An analysis task should be able to run for a day or longer. Why is there a timeout in rabbitmq involved anyway? Is there a rabbitmq connection that stays open for the duration of the analysis task?

**Comment by mcrot** [comment]
Rabbitmq has been replaced by Redis, I'm closing this. Reopen if there are similar problems with Redis.
