### ISSUE TITLE
An error occurred (500) when calling the HeadObject operation

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#812]
This error happened during saving a new datafile in the S3 storage:
```python3
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/formtools/wizard/views.py", line 244, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/formtools/wizard/views.py", line 302, in post
    return self.render_done(form, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/formtools/wizard/views.py", line 358, in render_done
    done_response = self.done(list(final_forms.values()), form_dict=final_forms, **kwargs)
  File "/app/topobank/manager/views.py", line 409, in done
    d['datafile'] = default_storage.save(new_path, File(datafile))
  File "/opt/conda/lib/python3.7/site-packages/django/core/files/storage.py", line 53, in save
    name = self.get_available_name(name, max_length=max_length)
  File "/opt/conda/lib/python3.7/site-packages/storages/backends/s3boto3.py", line 605, in get_available_name
    return super().get_available_name(name, max_length)
  File "/opt/conda/lib/python3.7/site-packages/django/core/files/storage.py", line 91, in get_available_name
    while self.exists(name) or (max_length and len(name) > max_length):
  File "/opt/conda/lib/python3.7/site-packages/storages/backends/s3boto3.py", line 469, in exists
    self.connection.meta.client.head_object(Bucket=self.bucket_name, Key=name)
  File "/opt/conda/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)

Exception Type: ClientError at /manager/surface/1316/new-topography/
Exception Value: An error occurred (500) when calling the HeadObject operation (reached max retries: 4): Internal Server Error
```

**Comment by mcrot** [comment]
Probably this error is an fact a "not found" error and should be status 404, but due to problems in some storage nodes (one node is not reachable) it cannot be decided that it is not available.
