### ISSUE TITLE
Redis error while triggering analyses

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#822]
Seen with version 0.20.1:
```
Triggered analysis for function 'Curvature distribution' and subject 'Topography 'sty_A1_SU.028_150um_site6.txt' from 2021-07-17'.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 524, in _ensured
    return fun(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kombu/messaging.py", line 203, in _publish
    timeout=timeout
  File "/opt/conda/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 597, in basic_publish
    return self._put(routing_key, message, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kombu/transport/redis.py", line 953, in _put
    client.lpush(self._q_for_pri(queue, pri), dumps(message))
  File "/opt/conda/lib/python3.7/site-packages/redis/commands/core.py", line 1963, in lpush
    return self.execute_command("LPUSH", name, *values)
  File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1180, in execute_command
    lambda error: self._disconnect_raise(conn, error),
  File "/opt/conda/lib/python3.7/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1178, in <lambda>
    conn, command_name, *args, **options
  File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1153, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1192, in parse_response
    response = connection.read_response()
  File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 829, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 447, in _reraise_as_library_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 545, in _ensured
    reraise_as_library_errors=False,
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 438, in _ensure_connection
    callback, timeout=timeout
  File "/opt/conda/lib/python3.7/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 878, in _connection_factory
    self._connection = self._establish_connection()
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 813, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/conda/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 947, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/opt/conda/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 925, in create_channel
    channel = self.Channel(connection)
  File "/opt/conda/lib/python3.7/site-packages/kombu/transport/redis.py", line 679, in __init__
    self.client.ping()
  File "/opt/conda/lib/python3.7/site-packages/redis/commands/core.py", line 954, in ping
    return self.execute_command("PING", **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1180, in execute_command
    lambda error: self._disconnect_raise(conn, error),
  File "/opt/conda/lib/python3.7/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1178, in <lambda>
    conn, command_name, *args, **options
  File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1152, in _send_command_parse_response
    conn.send_command(*args)
  File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 796, in send_command
    self.pack_command(*args), check_health=kwargs.get("check_health", True)
  File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 772, in send_packed_command
    self.check_health()
  File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 764, in check_health
    self.retry.call_with_retry(self._send_ping, self._ping_failed)
  File "/opt/conda/lib/python3.7/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 754, in _send_ping
    if str_if_bytes(self.read_response()) != "PONG":
  File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 829, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/conda/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/conda/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/conda/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/topobank/analysis/management/commands/trigger_analyses.py", line 157, in handle
    self.parse_item(item, use_default_kwargs=options['use_default_kwargs'], related=options['related'])
  File "/app/topobank/analysis/management/commands/trigger_analyses.py", line 136, in parse_item
    submit_analysis(users, obj, subject)
  File "/app/topobank/analysis/utils.py", line 239, in submit_analysis
    transaction.on_commit(lambda: perform_analysis.delay(analysis.id))
  File "/opt/conda/lib/python3.7/site-packages/django/db/transaction.py", line 128, in on_commit
    get_connection(using).on_commit(func)
  File "/opt/conda/lib/python3.7/site-packages/django/db/backends/base/base.py", line 645, in on_commit
    func()
  File "/app/topobank/analysis/utils.py", line 239, in <lambda>
    transaction.on_commit(lambda: perform_analysis.delay(analysis.id))
  File "/opt/conda/lib/python3.7/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/celery/app/task.py", line 579, in apply_async
    **options
  File "/opt/conda/lib/python3.7/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/opt/conda/lib/python3.7/site-packages/celery/app/amqp.py", line 519, in send_task_message
    **properties
  File "/opt/conda/lib/python3.7/site-packages/kombu/messaging.py", line 180, in publish
    exchange_name, declare, timeout
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 557, in _ensured
    errback and errback(exc, 0)
  File "/opt/conda/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.7/site-packages/kombu/connection.py", line 451, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**Comment by mcrot** [comment]
It seems this was caused by a full disk. Closing.
