### ISSUE TITLE
Redis connection error

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#823]
Just seen with Version 0.20.1:
```
022-04-13T16:28:25.475546481Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | [2022-04-13 18:28:25,470: ERROR/ForkPoolWorker-6] Task topobank.taskapp.tasks.perform_analysis[3c7e2266-a436-4de7-8de9-d10ef939e1e5] raised unexpected: ConnectionError('Error 104 while writing to socket. Connection reset by peer.')
2022-04-13T16:28:25.475572300Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | Traceback (most recent call last):
2022-04-13T16:28:25.475575885Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/django_redis/cache.py", line 31, in _decorator
2022-04-13T16:28:25.475578698Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return method(self, *args, **kwargs)
2022-04-13T16:28:25.475581329Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/django_redis/cache.py", line 80, in set
2022-04-13T16:28:25.475584416Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return self.client.set(*args, **kwargs)
2022-04-13T16:28:25.475587162Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/django_redis/client/default.py", line 185, in set
2022-04-13T16:28:25.475589770Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     raise ConnectionInterrupted(connection=client) from e
2022-04-13T16:28:25.475592352Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 104 while writing to socket. Connection reset by peer.
2022-04-13T16:28:25.475594935Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | 
2022-04-13T16:28:25.475597517Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | During handling of the above exception, another exception occurred:
2022-04-13T16:28:25.475600122Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | 
2022-04-13T16:28:25.475602691Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | Traceback (most recent call last):
2022-04-13T16:28:25.475605216Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
2022-04-13T16:28:25.475607742Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     R = retval = fun(*args, **kwargs)
2022-04-13T16:28:25.475610350Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
2022-04-13T16:28:25.475612862Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return self.run(*args, **kwargs)
2022-04-13T16:28:25.475615511Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/app/topobank/taskapp/tasks.py", line 131, in perform_analysis
2022-04-13T16:28:25.475617990Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     result = analysis.function.eval(subject, **kwargs)
2022-04-13T16:28:25.475620485Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/app/topobank/analysis/models.py", line 290, in eval
2022-04-13T16:28:25.475623455Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return self.get_implementation(subject_type).eval(subject, **kwargs)
2022-04-13T16:28:25.475627275Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/app/topobank/analysis/models.py", line 342, in eval
2022-04-13T16:28:25.475630035Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return pyfunc(subject, **kwargs)
2022-04-13T16:28:25.475632509Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/app/topobank/analysis/functions.py", line 348, in curvature_distribution
2022-04-13T16:28:25.475634979Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     topography = topography.topography()
2022-04-13T16:28:25.475637465Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/app/topobank/manager/models.py", line 783, in topography
2022-04-13T16:28:25.475640166Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     cache.set(cache_key, topo)
2022-04-13T16:28:25.475642988Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/django_redis/cache.py", line 38, in _decorator
2022-04-13T16:28:25.475649508Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     raise e.__cause__
2022-04-13T16:28:25.475652473Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/django_redis/client/default.py", line 175, in set
2022-04-13T16:28:25.475655881Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return bool(client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx))
2022-04-13T16:28:25.475658804Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/commands/core.py", line 1673, in set
2022-04-13T16:28:25.475661679Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return self.execute_command("SET", *pieces, **options)
2022-04-13T16:28:25.475664384Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1180, in execute_command
2022-04-13T16:28:25.475667215Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     lambda error: self._disconnect_raise(conn, error),
2022-04-13T16:28:25.475670149Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/retry.py", line 48, in call_with_retry
2022-04-13T16:28:25.475672903Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     fail(error)
2022-04-13T16:28:25.475686544Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1180, in <lambda>
2022-04-13T16:28:25.475688995Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     lambda error: self._disconnect_raise(conn, error),
2022-04-13T16:28:25.475691323Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1166, in _disconnect_raise
2022-04-13T16:28:25.475693598Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     raise error
2022-04-13T16:28:25.475695841Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/retry.py", line 45, in call_with_retry
2022-04-13T16:28:25.475698150Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     return do()
2022-04-13T16:28:25.475700335Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1178, in <lambda>
2022-04-13T16:28:25.475702640Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     conn, command_name, *args, **options
2022-04-13T16:28:25.475704918Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/client.py", line 1152, in _send_command_parse_response
2022-04-13T16:28:25.475707164Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     conn.send_command(*args)
2022-04-13T16:28:25.475709529Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 796, in send_command
2022-04-13T16:28:25.475711876Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     self.pack_command(*args), check_health=kwargs.get("check_health", True)
2022-04-13T16:28:25.475714137Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/redis/connection.py", line 788, in send_packed_command
2022-04-13T16:28:25.475716391Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    |     raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
2022-04-13T16:28:25.475718640Z prodstack_celeryworker.2.sh91bio1v4dl@conengrk    | redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
```

**Comment by mcrot** [comment]
Maybe this is related to having bwcloud's analyses instance in the swarm. Haven' t got to get this working again,
it couldn't connect to the database. After removing this node from the swarm, the celeryworker works again.
Strange.

**Comment by mcrot** [comment]
Doesn't happen in the last weeks. There might have been network problems. The bwcloud instance is included again.
I'll move this from the 0.21 milestone to the next one.  If it hasn't happened again, we can close it.

**Comment by mcrot** [comment]
Seems to be okay now. Reopen if this happens again.
