### ISSUE TITLE
Error during analysis: autocorrelation_for_surface() got an unexpected keyword argument 'num_points'

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#833]
```python
[2022-05-11 14:51:54,603: ERROR/ForkPoolWorker-1] Task topobank.taskapp.tasks.perform_analysis[5683d589-f60e-456e-94db-fa46b677e168] raised unexpected: TypeError("autocorrelation_for_surface() got an unexpected keyword argument 'num_points'")
Traceback (most recent call last):
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/taskapp/tasks.py", line 135, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/models.py", line 316, in eval
    return self.get_implementation(subject_type).eval(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/models.py", line 368, in eval
    return pyfunc(subject, **kwargs)
TypeError: autocorrelation_for_surface() got an unexpected keyword argument 'num_points'
```

**Comment by mcrot** [comment]
There was one analysis which had in its `kwargs` not only the key `nb_points_per_decade` but also the invalid and probably
former valid key `num_points`. Removed that key and recalculated the analysis.
