### ISSUE TITLE
scale_dependent_roughness_parameter: distances not defined yet

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#836]
```
2022-05-20T11:46:29.247761339Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    | [2022-05-20 13:46:29,247: ERROR/ForkPoolWorker-3] Task topobank.taskapp.tasks.perform_analysis[be09a163-dc39-476b-9da3-07030009b888] raised unexpected: UnboundLocalError("local variable 'distances' referenced before assignment")
2022-05-20T11:46:29.247803323Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    | Traceback (most recent call last):
2022-05-20T11:46:29.247810006Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
2022-05-20T11:46:29.247814054Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     R = retval = fun(*args, **kwargs)
2022-05-20T11:46:29.247818534Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
2022-05-20T11:46:29.247823086Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     return self.run(*args, **kwargs)
2022-05-20T11:46:29.247826422Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/app/topobank/taskapp/tasks.py", line 131, in perform_analysis
2022-05-20T11:46:29.247828956Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     result = analysis.function.eval(subject, **kwargs)
2022-05-20T11:46:29.247831494Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/app/topobank/analysis/models.py", line 290, in eval
2022-05-20T11:46:29.247848696Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     return self.get_implementation(subject_type).eval(subject, **kwargs)
2022-05-20T11:46:29.247851014Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/app/topobank/analysis/models.py", line 342, in eval
2022-05-20T11:46:29.247853144Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     return pyfunc(subject, **kwargs)
2022-05-20T11:46:29.247855534Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/app/topobank/analysis/functions.py", line 871, in scale_dependent_curvature
2022-05-20T11:46:29.247858067Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     nb_points_per_decade=nb_points_per_decade)
2022-05-20T11:46:29.247860367Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/app/topobank/analysis/functions.py", line 767, in scale_dependent_roughness_parameter
2022-05-20T11:46:29.247862499Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     process_series_reliable_unreliable(xname, x_kwargs, is_reliable_visible=True)
2022-05-20T11:46:29.247864604Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |   File "/app/topobank/analysis/functions.py", line 753, in process_series_reliable_unreliable
2022-05-20T11:46:29.247866860Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    |     progress_offset += len(distances)
2022-05-20T11:46:29.247869006Z prodstack_celeryworker.1.25wf2y4ff70y@conengrk    | UnboundLocalError: local variable 'distances' referenced before assignment
```
Seen with version 0.20.1.

**Comment by mcrot** [comment]
Duplicate of #790. Will be fixed in next release.
