### ISSUE TITLE
Sometimes "File not found" error when uploading files

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#906]
Example:
```
Internal Server Error: /manager/surface/1580/new-topography/

FileNotFoundError at /manager/surface/1580/new-topography/
[Errno 2] No such file or directory: '/app/media/topographies/wizard/Q50_100X_3x3_TO_UPLOAD.dat'

Request Method: POST
Request URL: https://contact.engineering/manager/surface/1580/new-topography/?redirect=/manager/surface/1580/&X-Progress-ID=b3aaeeb0-d01c-4216-affc-5bb51bf5cdd2
Django Version: 3.2.15
Python Executable: /opt/conda/bin/python
Python Version: 3.9.7
Python Path: ['/app', '/app', '/opt/conda/bin', '/opt/conda/lib/python39.zip', '/opt/conda/lib/python3.9', '/opt/conda/lib/python3.9/lib-dynload', '/opt/conda/lib/python3.9/site-packages', '/app/topobank']
Server time: Sun, 09 Oct 2022 21:25:49 +0200
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'collectfast',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.postgres',
 'crispy_forms',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.orcid',
 'rest_framework',
 'fontawesomefree',
 'formtools',
 'bokeh',
 'termsandconditions',
 'storages',
 'guardian',
 'bootstrap_datepicker_plus',
 'django_select2',
 'django_tables2',
 'progressbarupload',
 'celery_progress',
 'notifications',
 'django_filters',
 'tagulous',
 'trackstats',
 'fullurl',
 'topobank.users.apps.UsersAppConfig',
 'topobank.manager.apps.ManagerAppConfig',
 'topobank.analysis.apps.AnalysisAppConfig',
 'topobank.usage_stats.apps.UsageStatsAppConfig',
 'topobank.tabnav.apps.TabNavAppConfig',
 'topobank.publication.apps.PublicationAppConfig',
 'topobank.taskapp.celery.CeleryAppConfig',
 'gunicorn']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'termsandconditions.middleware.TermsAndConditionsRedirectMiddleware',
 'topobank.middleware.anonymous_user_middleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'topobank.usage_stats.middleware.count_request_middleware']


Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/formtools/wizard/views.py", line 244, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/formtools/wizard/views.py", line 291, in post
    form = self.get_form(data=self.request.POST, files=self.request.FILES)
  File "/opt/conda/lib/python3.9/site-packages/formtools/wizard/views.py", line 411, in get_form
    kwargs = self.get_form_kwargs(step)
  File "/app/topobank/manager/views.py", line 300, in get_form_kwargs
    step0_data = self.get_cleaned_data_for_step('upload')
  File "/opt/conda/lib/python3.9/site-packages/formtools/wizard/views.py", line 497, in get_cleaned_data_for_step
    files=self.storage.get_step_files(step),
  File "/opt/conda/lib/python3.9/site-packages/formtools/wizard/storage/base.py", line 101, in get_step_files
    file=self.file_storage.open(tmp_name), **field_dict)
  File "/opt/conda/lib/python3.9/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/opt/conda/lib/python3.9/site-packages/django/core/files/storage.py", line 243, in _open
    return File(open(self.path(name), mode))

Exception Type: FileNotFoundError at /manager/surface/1580/new-topography/
Exception Value: [Errno 2] No such file or directory: '/app/media/topographies/wizard/Q50_100X_3x3_TO_UPLOAD.dat'
```
This happens after uploading the file:
```
topography_create_wizard-current_step = 'metadata'
metadata-data_source = '0'
metadata-name = 'Q50_100X_3x3_TO_UPLOAD.dat'
metadata-measurement_date = '2022-10-09'
metadata-description = 'Q50 (100X)'
metadata-tags = ''
save = 'Next'
redirect = '/manager/surface/1580/'
```

**Comment by pastewka** [comment]
Resolved with #1012
