### ISSUE TITLE
django.db.utils.DataError: value too long for type character varying(160)

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/topobank#953]
After importing 10 surface containers, selecting the 10 new entries in the web gui and kicking off analysis, django throws

```
DataError

django.db.utils.DataError: value too long for type character varying(160)

Traceback (most recent call last)

    File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

    The above exception was the direct cause of the following exception:
    File "/usr/local/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 133, in __call__

    response = self.get_response(request)

    File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 130, in get_response

    response = self._middleware_chain(request)

    File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 49, in inner

    response = response_for_exception(request, exc)

    File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception

    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())

    File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception

    return debug.technical_500_response(request, *exc_info)

    File "/usr/local/lib/python3.10/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response

    raise exc_value.with_traceback(tb)

    File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner

    response = get_response(request)

    File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

    File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner

    return func(*args, **kwds)

    File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view

    return view_func(request, *args, **kwargs)

    File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view

    return self.dispatch(request, *args, **kwargs)

    File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch

    return handler(request, *args, **kwargs)

    File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 133, in get

    return self.render_to_response(self.get_context_data())

    File "/app-topobank/topobank/analysis/views.py", line 1007, in get_context_data

    effective_topographies, effective_surfaces, subjects_ids_json = selection_to_subjects_json(self.request)

    File "/app-topobank/topobank/manager/utils.py", line 719, in selection_to_subjects_json

    coll = SurfaceCollection.objects.create(name='Surfaces: '+", ".join(s.name for s in effective_surfaces))

    File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

    File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create

    obj.save(force_insert=True, using=self.db)

    File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save

    self.save_base(using=using, force_insert=force_insert,

    File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base

    updated = self._save_table(

    File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table

    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)

    File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert

    return manager._insert(

    File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

    File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

    File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql

    cursor.execute(sql, params)

    File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 230, in execute

    return self._record(self.cursor.execute, sql, params)

    File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 154, in _record

    return method(sql, params)

    File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute

    return super().execute(sql, params)

    File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

    File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers

    return executor(sql, params, many, context)

    File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute

    with self.db.wrap_database_errors:

    File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

    File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

    django.db.utils.DataError: value too long for type character varying(160)

```

**Comment by jotelha** [comment]
Maybe store only the first n full names + a number m, i.e. "Surface A, Surface B, and 5 more" as soon as the field width is exceeded?

**Comment by mcrot** [comment]
Good idea!
